#!/usr/bin/env python3
"""Generate symbol-address declarations and an iOS linker stub (no Apple libs)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
source = ROOT / "compat/ios/runner/abi/cxx-symbols.txt"
names = [line for line in source.read_text().splitlines() if line and not line.startswith("#")]
if len(set(names)) != len(names) or any(not name.startswith("_") for name in names):
    raise ValueError("invalid/duplicate C++ symbol")
lines = ["/* SPDX-License-Identifier: GPL-2.0-or-later */",
    "/* Generated by build-support/ios/generate-cxx-symbols.py. */",
    "#ifndef VINIX_IOS_CXX_SYMBOLS_H", "#define VINIX_IOS_CXX_SYMBOLS_H",
    "#include <stdint.h>", "#include <string.h>"]
for index, name in enumerate(names):
    lines.append(f'extern const unsigned char ios_cxx_{index}[] __asm__("{name[1:]}");')
lines.append("static uintptr_t ios_cxx_symbol(const char *name) {")
for index, name in enumerate(names):
    lines.append(f'    if (!strcmp(name, "{name}")) return (uintptr_t)ios_cxx_{index};')
lines += ["    return 0;", "}", "#endif", ""]
(source.parent / "cxx-symbols.h").write_text("\n".join(lines))
names.remove("__Unwind_Resume")  # This symbol belongs to libSystem in Darwin.
(ROOT / "tests/ios/libcxx.tbd").write_text(
    "--- !tapi-tbd\ntbd-version: 4\ntargets: [ arm64-ios ]\n"
    "install-name: '/usr/lib/libc++.1.dylib'\nexports:\n  - targets: [ arm64-ios ]\n"
    "    symbols: [\n      " + ",\n      ".join(names) + "\n    ]\n...\n")
