// SPDX-License-Identifier: GPL-2.0-or-later
module cachekey

const desktop_source_paths = [
	'scripts/build-desktop-aarch64.sh',
	'build-support/content-key.py',
	'build-support/musl/stage.py',
	'build-support/musl/malloc-retain.patch',
	'build-support/musl/alpine',
	'build-support/musl/alpine-1.2.6',
	'build-support/desktop-build-key.py',
	'desktop',
	'ui2:v.mod',
	'ui2:ui',
	'ui2:uikit',
	'ui2:windows',
	'ui2:linux',
	'ui2:assets',
	'ui2:examples',
	'build-support/aarch64-cc-shim',
	'build-support/init-aarch64/initcore',
	'build-support/init-aarch64/syscall_abi.S',
	'build-support/init-aarch64/syscall_abi.h',
	'build-support/init-aarch64/compile-v.py',
	'tools/m1-wifi/compile-v.py',
	'tools/m1-wifi/wifi_v.h',
	'tools/m1-wifi/core/core.v',
	'kernel/c',
	'build-support/vinix-pkg',
	'build-support/v-command',
	'build-support/java-cacerts.py',
	'build-support/minecraft',
	'build-support/doom',
	'build-support/vinix-desktop-build',
	'build-support/vinix-desktop-reload',
	'build-support/vinix-host-sync',
	'build-support/xorg-server/startx',
	'build-support/xorg-server/winehost',
	'build-support/xorg-server/wine-host-v-abi.h',
	'build-support/xorg-server/compile-v-host.py',
	'build-support/xorg-server/xinputcore',
	'build-support/xorg-server/xinput_abi.h',
	'build-support/xorg-server/build-wine-host.sh',
	'build-support/compile-v-module.py',
	'build-support/x86-translation/officecore',
	'build-support/x86-translation/compile-v-office.py',
	'build-support/x86-translation/sppc-office-v-abi.h',
	'build-support/x86-translation/sppc-office.def',
	'build-support/firefox',
	'build-support/gimp',
	'build-support/libreoffice',
	'build-support/chromium',
	'build-support/hyprland',
	'build-support/roblox',
	'build-support/android',
	'gl-triangle/run-m1-agx-smoke',
	'gl-triangle/eglcore',
	'gl-triangle/glutcore',
	'gl-triangle/legacycore',
	'gl-triangle/gl_v.h',
	'gl-triangle/compile-v.py',
	'gl-triangle/stage.py',
	'tests/browsers/firefox-smoke.html',
	'tests/browsers/chromium-smoke.html',
	'tests/packages/x-window-check.py',
	'build/wallpapers-cache',
]

const desktop_layer_defaults = [
	DesktopLayer{'VINIX_PYTHON_STAGING', 'build-aarch64-python/staging'},
	DesktopLayer{'VINIX_NETWORK_TOOLS_STAGING', 'build-aarch64-network-tools/staging'},
	DesktopLayer{'VINIX_VLANG_STAGING', 'build-aarch64-v/staging'},
	DesktopLayer{'VINIX_X11_STAGING', 'build-aarch64-x11/staging'},
	DesktopLayer{'VINIX_FIREFOX_STAGING', 'build-aarch64-firefox/staging'},
	DesktopLayer{'VINIX_CHROMIUM_STAGING', 'build-aarch64-chromium/staging'},
	DesktopLayer{'VINIX_LIBREOFFICE_STAGING', 'build-aarch64-libreoffice/staging'},
	DesktopLayer{'VINIX_MINECRAFT_STAGING', 'build-aarch64-minecraft/staging'},
	DesktopLayer{'VINIX_DOOM_STAGING', 'build-aarch64-doom/staging'},
	DesktopLayer{'VINIX_ASAHI_STAGING', 'build-aarch64-asahi/staging'},
	DesktopLayer{'VINIX_HYPRLAND_STAGING', 'build-aarch64-hyprland/staging'},
	DesktopLayer{'VINIX_BLENDER_NATIVE_STAGING', 'build-aarch64-blender-native/staging'},
	DesktopLayer{'VINIX_X86_TRANSLATION_STAGING', 'build-aarch64-x86-translation/staging'},
	DesktopLayer{'VINIX_ROBLOX_STAGING', 'build-aarch64-roblox/aarch64/staging'},
	DesktopLayer{'VINIX_ANDROID_STAGING', 'build-aarch64-android/aarch64/staging'},
]

const desktop_layer_order = [
	'VINIX_PYTHON_STAGING',
	'VINIX_NETWORK_TOOLS_STAGING',
	'VINIX_VLANG_STAGING',
	'VINIX_FIREFOX_STAGING',
	'VINIX_CHROMIUM_STAGING',
	'VINIX_LIBREOFFICE_STAGING',
	'VINIX_MINECRAFT_STAGING',
	'VINIX_DOOM_STAGING',
	'VINIX_ASAHI_STAGING',
	'VINIX_HYPRLAND_STAGING',
	'VINIX_BLENDER_NATIVE_STAGING',
	'VINIX_X86_TRANSLATION_STAGING',
	'VINIX_ROBLOX_STAGING',
	'VINIX_ANDROID_STAGING',
]
