#! /bin/sh

name=at-spi2-core
version=2.56.2
revision=1
tarball_url="https://download.gnome.org/sources/at-spi2-core/2.56/at-spi2-core-${version}.tar.xz"
tarball_blake2b="12dff02209243cde88108eced8b2757bdce3dff20eff95a362d00de610374aabeedbc8878a60c11ac28f0e71918f74caf0083c07d652bd06b656c27d4238579f"
imagedeps="meson ninja-build libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs bash dbus glib gsettings-desktop-schemas libx11 libxi libxkbcommon libxml libxtst"

configure() {
    meson_configure \
        -Dsystemd_user_dir=/tmp \
        -Dintrospection=disabled
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
