#! /bin/sh

name=at-spi2-core
version=2.54.1
revision=1
tarball_url="https://download.gnome.org/sources/at-spi2-core/2.54/at-spi2-core-${version}.tar.xz"
tarball_blake2b="b1a1657081f22623bba7730f687dc69e4b7c1562020edc42b29f0a8842ea8443021aab1b8fd23d75877c8023c43c586ce70640be42fef5663983381018e9e80b"
imagedeps="meson ninja-build libglib2.0-dev"
hostdeps="gcc pkg-config"
deps="core-libs bash dbus glib gsettings-desktop-schemas libx11 libxi libxkbcommon libxml libxtst"

configure() {
    meson_configure \
        -Dsystemd_user_dir=/tmp \
        -Dintrospection=disabled
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
