#! /bin/sh

name=base
skip_pkg_check=yes
version=0.0
revision=1
deps="base-files kernel init bash binutils bzip2 coreutils diffutils findutils gawk gcc gmp grep gzip less make mpc mpfr nano ncurses pcre2 readline sed tar tzdata util-vinix xbps xz zlib zstd"
