#! /bin/sh

name=cglm
version=0.9.6
revision=1
tarball_url="https://github.com/recp/cglm/archive/refs/tags/v${version}.tar.gz"
tarball_blake2b="a51bfb6d9198f4ecf6b1bcc56b346df963e56d5229c226bfa6d3bdccfbb3e25c30e33eccfc3614402a61286e9e87dc1e63e2b8f22e4d0fd640232f40b5a4db70"
source_hostdeps="automake autoconf libtool pkg-config"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
