#! /bin/sh

name=curl
version=8.13.0
revision=1
tarball_url="https://curl.se/download/curl-${version}.tar.xz"
tarball_blake2b="6869634ad50f015d5c7526699034d5a3f27d9588bc32eacc8080dbd6c690f63b1f25cee40d3fdf8fd9dd8535c305ea9c5edf1d5a02bc6d9ce60fd8c88230aca0"
hostdeps="gcc pkg-config"
deps="core-libs openssl zlib zstd libpsl"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-threaded-resolver \
        --with-openssl
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
