#! /bin/sh

name=diffutils
version=3.12
revision=1
tarball_url="https://ftp.gnu.org/gnu/diffutils/diffutils-${version}.tar.xz"
tarball_blake2b="5b4593b39da71578d7f975603abe9359be215b9ac76548a6ab0d6e3838bb103c7ffcddf7fa01abcd5c6289db9a2f16b43aa3d5e846a9aa4b8db866763c2660de"
hostdeps="gcc pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
        gl_cv_func_strcasecmp_works=yes \
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
