#! /bin/sh

name=freestnd-c-hdrs
version=87956bbcad0e1934e708223913be53131311342d
revision=1
git_url="https://github.com/osdev0/freestnd-c-hdrs.git"
commit=${version}

build() {
    cp -rpf "${source_dir}"/. ./
}

package() {
    DESTDIR="${dest_dir}" PREFIX="${prefix}" make install
}
