#! /bin/sh

name=freestnd-cxx-hdrs
version=1cc6d4665e1e0ce4408c94616c8c4de4c19b9968
revision=1
git_url="https://github.com/osdev0/freestnd-cxx-hdrs.git"
commit=${version}

build() {
    cp -rpf "${source_dir}"/. ./
}

package() {
    DESTDIR="${dest_dir}" PREFIX="${prefix}" make install
}
