#! /bin/sh

name=fribidi
version=1.0.16
revision=1
tarball_url="https://github.com/fribidi/fribidi/releases/download/v${version}/fribidi-${version}.tar.xz"
tarball_blake2b="9a0dce6152ba0f0ca4a42a83ca0f6d234fb9fef2a681d274aab6922e3394b70430e677fd549b17b13d928d733c0e72a7e3527cfb461971bbfd155ec1bd5e738c"
imagedeps="meson ninja-build build-essential"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
