#! /bin/sh

name=gl-triangle
skip_pkg_check=yes
version=1.0
revision=1
source_dir="gl-triangle"
hostdeps="gcc"
deps="core-libs freeglut gcc mesa xf86-video-fbdev xorg-server xorg-xinit"

build() {
    ${OS_TRIPLET}-gcc \
        $TARGET_CFLAGS \
        $TARGET_LDFLAGS \
        "${source_dir}"/triangle.c \
        -o gl-triangle \
        -lglut -lGL -lm
}

package() {
    mkdir -p \
        "${dest_dir}"/usr/bin \
        "${dest_dir}"/usr/share/examples/gl-triangle \
        "${dest_dir}"/var/lib/xkb

    cp -v gl-triangle "${dest_dir}"/usr/bin/
    cp -v "${source_dir}"/run-gl-triangle "${dest_dir}"/usr/bin/
    chmod +x "${dest_dir}"/usr/bin/run-gl-triangle
    cp -v "${source_dir}"/triangle.c \
        "${dest_dir}"/usr/share/examples/gl-triangle/

    post_package_strip
}
