#! /bin/sh

name=less
version=668
revision=1
tarball_url="https://www.greenwoodsoftware.com/less/less-${version}.tar.gz"
tarball_blake2b="0f6a85a1c66577dd2a28682a6f8399e42fdbe9fc1498b2e89c6bb7c47109e8d3ab934abe5dd998b2c8dfacfb174ad9daeb79b3d4c13df22fa035ea792b2eaf5e"
source_hostdeps="autoconf automake libtool pkg-config"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs ncurses"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"

    post_package_strip
}
