#! /bin/sh

name=libgpg-error
version=1.49
revision=1
tarball_url="https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-${version}.tar.gz"
tarball_blake2b="fc8d336f2c91f8855e44b0daf67f82e24877caac3bf4dcfc42c6346cd72caf8f4d99977b66544896414a26550c7ff7c005ca8fd932938588c50141d5cd1b5fe9"
source_hostdeps="automake autoconf libtool pkg-config"
imagedeps="build-essential"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs"

prepare() {
    cp -v src/syscfg/lock-obj-pub.$ARCHITECTURE-unknown-linux-gnu.h src/syscfg/lock-obj-pub.vinix-mlibc.h

    autotools_recursive_regen
}

configure() {
    cp -rp "${source_dir}"/. ./

        configure_script_path=./configure \
    autotools_configure \
        CFLAGS_FOR_BUILD="$HOST_CFLAGS" \
        CXXFLAGS_FOR_BUILD="$HOST_CXXFLAGS" \
        LDFLAGS_FOR_BUILD="$HOST_LDFLAGS"
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
