#! /bin/sh

name=libice
version=1.1.2
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libICE-${version}.tar.gz"
tarball_blake2b="4715895d10490c526d72032653f52b04d3c3d8f1b6be9fb2ff65a081c5dfccbaa14932588e24a16c8c48e6cc6b348c53f8ce1ccba82e8ca0bbf645b0f82123cd"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="xorg-util-macros xtrans"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs xorg-proto xtrans"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
