#! /bin/sh

name=libpipeline
version=1.5.8
revision=1
tarball_url="https://download.savannah.nongnu.org/releases/libpipeline/libpipeline-${version}.tar.gz"
tarball_blake2b="1feb1a9493fd0850b4e3e446619e7e042bd97d8c0bbb3e13a91d90d6cde3ca2c17fb8a3ca256f65291dadc4d8703ad5d3a795839bf8280adc4547b3ec3d2da7d"
source_hostdeps="automake autoconf libtool pkg-config"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
