#! /bin/sh

name=libsm
version=1.2.6
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libSM-${version}.tar.gz"
tarball_blake2b="90bb1c08acc213cf0fbb766505d3f0973dab0ac989d1c76e88ef26a6cfedeeb27a7db06f8d3a794514888bcbc9998939978ffb4371ede330f8b98f3cb48b7a1b"
hostdeps="gcc pkg-config"
deps="core-libs xorg-proto libice"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
