#! /bin/sh

name=libxtst
version=1.2.4
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libXtst-${version}.tar.gz"
tarball_blake2b="4d878d097bfd09857bf540732f4239dfb3a6e8773f153cf2fd38ab8e0500763c7bc974cc1bb5525e976a36bea7a9c1dd92934210be40b0fb1b1c181343bd20c5"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="xorg-util-macros"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs xorg-proto libxext libxi libx11"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
