#! /bin/sh

name=libxt
version=1.3.1
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libXt-${version}.tar.gz"
tarball_blake2b="124036245a76703a5bb2379fd0b6605dc665cc58b9df657cfc3b0214574dcad6f46490ee76be8ea7d157afa84940c5ee8edaca37983ff6ec7deb572f51985703"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="xorg-util-macros"
imagedeps="build-essential"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs libx11 libsm"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-appdefaultdir=/etc/X11/app-defaults
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
