#! /bin/sh

name=libx11
version=1.8.10
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libX11-${version}.tar.xz"
tarball_blake2b="72ff400e1aad5bcb04e5dd3fb43f7767fad47e38cf628382cd5ffd5a204efc4de4f626027dddbbc7e10f80f8eaee0bcdf9792d9d012256366920f7ae0cffcb15"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="xtrans xorg-util-macros"
imagedeps="build-essential"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs xorg-proto libxcb xtrans"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-ipv6 \
        --with-keysymdefdir=${sysroot_dir}/usr/include/X11
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
