#! /bin/sh

name=libxcursor
version=1.2.3
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libXcursor-${version}.tar.gz"
tarball_blake2b="6f6df48d861b7ffa88dab6bdba850db46a5cbdfc080150365de2ae98bdb79a208a4d0caae4442fcc6ff81334d3d67c5ae16eca2aa627af705d0bc47db32151bb"
source_hostdeps="autoconf automake libtool pkg-config"
source_deps="xorg-util-macros"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs libxrender libxfixes libx11"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
