#! /bin/sh

name=libxcvt
version=0.1.3
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libxcvt-${version}.tar.xz"
tarball_blake2b="ae104743153077454ba8923d7b8bbe77d834e4795fd735de9e42617c3e49fd63052ad37214e7ab45e3f5884cd6038b60c0ff7c52f8a7892e0dea4630aaf0abad"
imagedeps="meson ninja-build"
hostdeps="gcc pkg-config"
deps="core-libs"

configure() {
    meson_configure
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
