#! /bin/sh

name=libxxf86vm
version=1.1.6
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libXxf86vm-${version}.tar.gz"
tarball_blake2b="403425049f78ecf8eeddd01797ea21d51853a0165d9d8ca9513b05d85b61d7cbddac91290fba054d1cca08f43b165efd2e441cf4ff3b4b7e9e5fe59a6daf7d3e"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="xorg-util-macros"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs xorg-proto libxext"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
