#! /bin/sh

name=libx11
version=1.8.12
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libX11-${version}.tar.xz"
tarball_blake2b="f4bdb69abb2add723ca84832ef35f239659228c1f5a3f53631f0d4d4afa7030512b9ba65479464f3efecca0e09d1f758e3b92b139dd5e716fac1b8caaf5bb98d"
imagedeps="build-essential"
hostdeps="gcc pkg-config"
deps="core-libs xorg-proto libxcb xtrans"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-keysymdefdir=${sysroot_dir}/usr/include/X11
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
