#! /bin/sh

name=libxrender
version=0.9.12
revision=1
tarball_url="https://www.x.org/archive/individual/lib/libXrender-${version}.tar.gz"
tarball_blake2b="27a8745b6c833022d7714114c6fdd80ef594e288e00a01bd5d4657e43c34558a338ff65cabdcc2065aa7dec7a8595c74277103ddae9aedf6ea2fe4ef7501dc73"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="xorg-util-macros"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs xorg-proto libx11"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
