#! /bin/sh

name=libzip
version=1.10.1
revision=1
tarball_url="https://github.com/nih-at/libzip/releases/download/v${version}/libzip-${version}.tar.xz"
tarball_blake2b="bd5e6ea92ebf1c1210aa4b6fc58f0060d7a87ef2f47ac8475a0e30d67bd7e44f5a7671faf50d670ccfcf4117c379a1b1704871f88ec95654cc2c971e29965018"
imagedeps="cmake ninja-build git"
hostdeps="gcc pkg-config"
deps="core-libs zlib bzip2 xz zstd openssl"

configure() {
    cmake_configure \
        -DENABLE_GNUTLS=OFF \
        -DBUILD_DOC=OFF
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
