#! /bin/sh

name=libzip
version=1.11.3
revision=1
tarball_url="https://github.com/nih-at/libzip/releases/download/v${version}/libzip-${version}.tar.xz"
tarball_blake2b="3296ff48ce853687ea4fbe310130c2468c87990da9a6c285acb09406afb23fe2240fb27a94c23db8b2ad58bd7b80f5b6e84d0702957792d0baddd13487c483dd"
imagedeps="cmake ninja-build git"
hostdeps="gcc pkg-config"
deps="core-libs zlib bzip2 xz zstd openssl"

configure() {
    cmake_configure \
        -DENABLE_GNUTLS=OFF \
        -DBUILD_DOC=OFF
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
