#! /bin/sh

name=limine
version=8.1.2
revision=1
tarball_url="https://github.com/limine-bootloader/limine/releases/download/v${version}/limine-${version}.tar.gz"
tarball_blake2b="b4517ed960686f7d854f71961134a32b5cc786026ad8064a543b86f0b971eeb7c6e38a4f1560484cfc4038e1ea71fe943c0a9d37da966ce0f302c307bf59d03b"
source_hostdeps="autoconf automake libtool pkg-config"
imagedeps="mtools nasm"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs"

prepare() {
    autotools_recursive_regen
}

configure() {
    if [ "$ARCHITECTURE" = "x86_64" ]; then
        X86_FLAGS="--enable-bios \
                   --enable-bios-cd \
                   --enable-bios-pxe \
                   --enable-uefi-ia32 \
        "
    fi

    autotools_configure \
        $X86_FLAGS \
        --enable-uefi-$ARCHITECTURE \
        --enable-uefi-cd \
        TOOLCHAIN_FOR_TARGET=${OS_TRIPLET}
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
