#! /bin/sh

name=man-db
version=2.13.0
revision=1
tarball_url="https://download.savannah.nongnu.org/releases/man-db/man-db-${version}.tar.xz"
tarball_blake2b="7ce91a7abc6d3bbd92d4707f13caacd8ab5caee0502a2b115f8aa53f4d38df05b0e03346f70584618cce6f5457113e826828a02b847bff57abd6ba6ec1b2d407"
imagedeps="groff"
hostdeps="gcc pkg-config"
deps="core-libs bash gdbm groff less libpipeline zlib"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --disable-setuid \
        --with-systemdtmpfilesdir= \
        --with-systemdsystemunitdir= \
        --with-pager=${prefix}/bin/less
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
