#! /bin/sh

name=mesa
version=25.0.4
revision=1
tarball_url="https://archive.mesa3d.org/mesa-${version}.tar.xz"
tarball_blake2b="b661bc1534bff848c32c559ecc790fd7770682aa7f35403c2fb50b899ad83dbbafb2baecf0e372972849378a4a539eeafe5e9c9e1497ab4313ebcafa89f6e248"
imagedeps="meson ninja-build python3-mako python3-yaml glslang-tools"
hostdeps="gcc pkg-config"
deps="core-libs llvm libexpat libx11 libxcb libxext libxshmfence libxxf86vm libxrandr zlib zstd"

configure() {
    meson_configure \
        -Dglx=xlib \
        -Dplatforms=x11 \
        -Dgallium-drivers=llvmpipe,softpipe \
        -Dvulkan-drivers=swrast \
        -Dosmesa=true \
        -Dvideo-codecs=all
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
