#! /bin/sh

name=pixman
version=0.46.0
revision=1
tarball_url="https://www.x.org/archive/individual/lib/pixman-${version}.tar.xz"
tarball_blake2b="5fc9d0df2f685afc1931ac12757d7ec0369c1f90b51f79b696479a2edd0c13e0684938871166318ca5c78b4955195ba5517e98e4666803b9062f4ed2b6593afa"
imagedeps="meson ninja-build"
hostdeps="gcc pkg-config"
deps="core-libs libpng"

configure() {
    meson_configure
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
