#! /bin/sh

name=sdl3
version=3.2.10
revision=1
tarball_url="https://github.com/libsdl-org/SDL/releases/download/release-${version}/SDL3-${version}.tar.gz"
tarball_blake2b="32e33d4209582fd0889969b30700f793562c7cb0afa3fc05befe421d10e101f558f9c817c7cc7855d793d78339a4c5b01129f24a5981a5651271e14d2e5aeff8"
imagedeps="cmake ninja-build git"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxext libxcursor libxi libxfixes libxrandr libxrender libxxf86vm mesa"

configure() {
    cmake_configure \
        -DSDL_ALTIVEC=OFF \
        -DSDL_DISKAUDIO=OFF \
        -DSDL_OPENGL=ON \
        -DSDL_OPENGLES=ON \
        -DSDL_PTHREADS=ON \
        -DSDL_PTHREADS_SEM=OFF \
        -DSDL_OSS=OFF \
        -DSDL_ALSA=OFF \
        -DSDL_JACK=OFF \
        -DSDL_PULSEAUDIO=OFF \
        -DSDL_SNDIO=OFF \
        -DSDL_RPATH=OFF \
        -DSDL_X11=ON \
        -DSDL_WAYLAND=OFF \
        -DSDL_RPI=OFF \
        -DSDL_COCOA=OFF \
        -DSDL_DIRECTX=OFF \
        -DSDL_WASAPI=OFF \
        -DSDL_RENDER_D3D=OFF \
        -DSDL_VIVANTE=OFF \
        -DSDL_VULKAN=OFF \
        -DSDL_KMSDRM=OFF \
        -DSDL_HIDAPI=ON \
        -DSDL_SHARED=ON \
        -DSDL_STATIC=OFF \
        -DSDL_TEST_LIBRARY=OFF
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
