#! /bin/sh

name=taisei
version=1.4.2
revision=1
tarball_url="https://github.com/taisei-project/taisei/releases/download/v${version}/taisei-${version}.tar.xz"
tarball_blake2b="382e6e02013573f4218a073ad9d19cd128f0b4366d3f3f586e8ab4de9a5948ffedd13a22cefc9a8af04cccd2cf0205c9d6c738b125fd332b363606acd5938e4a"
imagedeps="meson ninja-build build-essential"
hostdeps="gcc pkg-config"
deps="core-libs freetype2 libpng sdl2-compat libwebp zlib cglm openssl"

configure() {
    meson_configure \
        -Ddocs=disabled \
        -Da_default=null \
        -Db_lto=false \
        -Da_sdl=disabled
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install

    post_package_strip
}
