#! /bin/sh

name=wine
version=10.0
revision=1
tarball_url="https://dl.winehq.org/wine/source/10.0/wine-${version}.tar.xz"
tarball_blake2b="92178cf484cf33e9f3b8340429ee8e68c36e0d25eee4a892f059ab73f103cfcb9eb15e1883bc9fd8c8fe311d4ccbb56582d1f780da7b1406a7839a13addd29ae"
imagedeps="build-essential flex bison gcc-mingw-w64-x86-64"
hostdeps="gcc pkg-config wine-tools"
deps="core-libs fontconfig freetype2 libx11 libxext libxcursor libxfixes libxi libxinerama libxrandr libxrender"

prepare() {
    autotools_recursive_regen
}

configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    "${source_dir}"/configure \
        --host="${OS_TRIPLET}" \
        --prefix="${prefix}" \
        --bindir="${prefix}/bin" \
        --libdir="${prefix}/lib" \
        --enable-win64 \
        --disable-tests \
        --with-wine-tools=/usr/local/lib/wine-tools \
        --with-x \
        --without-alsa \
        --without-capi \
        --without-coreaudio \
        --without-cups \
        --without-dbus \
        --without-ffmpeg \
        --without-gettext \
        --without-gettextpo \
        --without-gphoto \
        --without-gnutls \
        --without-gssapi \
        --without-gstreamer \
        --without-inotify \
        --without-krb5 \
        --without-netapi \
        --without-opencl \
        --without-opengl \
        --without-osmesa \
        --without-oss \
        --without-pcap \
        --without-pcsclite \
        --without-pulse \
        --without-sane \
        --without-sdl \
        --without-udev \
        --without-unwind \
        --without-usb \
        --without-v4l2 \
        --without-vulkan \
        --without-wayland \
        --without-xcomposite \
        --without-xshm \
        --without-xxf86vm
}

build() {
    make -j${parallelism}
    x86_64-w64-mingw32-gcc -Os -s \
        "${base_dir}"/tests/wine/smoke.c -o vinix-wine-smoke.exe
}

package() {
    DESTDIR="${dest_dir}" make install

    if ! [ -e "${dest_dir}${prefix}/bin/wine" ]; then
        ln -s wine64 "${dest_dir}${prefix}/bin/wine"
    fi

    install -D -m755 "${base_dir}"/tests/wine/wine-smoke \
        "${dest_dir}${prefix}"/bin/wine-smoke
    install -D -m644 vinix-wine-smoke.exe \
        "${dest_dir}${prefix}"/share/wine/vinix-wine-smoke.exe
}
