#! /bin/sh

name=xcb-util
version=0.4.1
revision=1
tarball_url="https://xcb.freedesktop.org/dist/xcb-util-${version}.tar.xz"
tarball_blake2b="bcde73073590c56771af6233f1a04a692197a756ef9ce70b6e0bd3625ad6d61f99f4c671dcfae39c8dd66e3225f40f7e9b42dd115ffe83a561e48a9808bf00e3"
hostdeps="gcc pkg-config"
deps="core-libs libxcb"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
