#! /bin/sh

name=xf86-input-keyboard
version=2.1.0
revision=1
tarball_url="https://www.x.org/releases/individual/driver/xf86-input-keyboard-${version}.tar.gz"
tarball_blake2b="a3d440b1e49df09ee50938a80c98c5274acaffd8824f0cb912844ae26831d3814c4cc2c23b52dbce88847a5bd33614b09b99f01d72ba102905e30166a52412f0"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="xorg-util-macros"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs xorg-server xorg-util-macros"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
