#! /bin/sh

name=xorg-xauth
repology_id=xauth
version=1.1.4
revision=1
tarball_url="https://www.x.org/releases/individual/app/xauth-${version}.tar.xz"
tarball_blake2b="60f693118531058e5114a80e0e34eb8a429c3ce0d8ef168fea21924afa21139abb58b63e64c745c69df7f7e2a0540636f9d5ab32ed6d0019f9bc7cfa92724a7e"
hostdeps="gcc pkg-config"
deps="core-libs libxmu libxau libxext libx11"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
