#! /bin/sh

name=xorg-xclock
repology_id=xclock
version=1.1.1
revision=1
tarball_url="https://xorg.freedesktop.org/archive/individual/app/xclock-${version}.tar.gz"
tarball_blake2b="4fd77b8f1f0962774dd0e6295f7482c05be8107e1606a9705ccd2864d2c9b37adda4a41a6704c6e1363edd2b7e704324799c4feaff39e218b326b66274b48187"
hostdeps="gcc pkg-config"
deps="core-libs libx11 libxmu libxaw libxrender libxft libxkbfile"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --with-appdefaultdir=/etc/X11/app-defaults
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
