#! /bin/sh

name=xorg-xsetroot
repology_id=xsetroot
version=1.1.3
revision=1
tarball_url="https://www.x.org/archive/individual/app/xsetroot-${version}.tar.gz"
tarball_blake2b="b904a9f622883d050751026966341daac1e31ac7c66a6bc54ee6e370c7f096aa5158c7fdc37feb796c7ff7720f654cf9ec194e4ecdb95a3049f3021afee2cb8e"
hostdeps="gcc pkg-config"
builddeps="xbitmaps"
deps="core-libs libx11 libxmu libxcursor"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
