#! /bin/sh

name=xorg-twm
repology_id=twm
version=1.0.13.1
revision=1
tarball_url="https://www.x.org/pub/individual/app/twm-${version}.tar.xz"
tarball_blake2b="ab965119974ca9a2079d1f6e5d51f44278debd2e231159fb39af2e5468e4e6620ed764baafc3b5df51366b639bc55b0d868fe876d2cfef07aac92656cfd471b9"
hostdeps="gcc pkg-config"
deps="core-libs libxmu"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
