#! /bin/sh

name=xtrans
version=1.5.2
revision=1
tarball_url="https://www.x.org/archive/individual/lib/xtrans-${version}.tar.gz"
tarball_blake2b="4eaf5a17e58446a23ac5d5138bb13a1a9121e8a9e05d3684f8aaac85c17dc904b5ba51607d82ff65f7bbe3f0c62ef96fa9c742e1d704edadf5b66e18e476e134"
source_hostdeps="automake autoconf libtool pkg-config"
source_deps="xorg-util-macros"
hostdeps="gcc autoconf automake libtool pkg-config"
deps="core-libs xorg-util-macros"

prepare() {
    autotools_recursive_regen
}

configure() {
    autotools_configure
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
