#! /bin/sh

JINX_MAJOR_VER=0.5

HOST_CFLAGS="-O2 -pipe -fstack-clash-protection"
HOST_CXXFLAGS="${HOST_CFLAGS} -Wp,-D_GLIBCXX_ASSERTIONS"
HOST_LDFLAGS="-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now"

TARGET_CFLAGS="$HOST_CFLAGS"
TARGET_CXXFLAGS="$HOST_CXXFLAGS"
TARGET_LDFLAGS="$HOST_LDFLAGS"

if [ -z "$ARCHITECTURE" ]; then
    ARCHITECTURE=x86_64
fi

JINX_ARCH=${ARCHITECTURE}

OS_TRIPLET=$ARCHITECTURE-vinix-mlibc

case "$ARCHITECTURE" in
    x86_64)
        TARGET_CFLAGS="$TARGET_CFLAGS -march=x86-64 -mtune=generic -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
        TARGET_CXXFLAGS="$TARGET_CXXFLAGS -march=x86-64 -mtune=generic -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
        TARGET_LDFLAGS="$TARGET_LDFLAGS -Wl,-z,pack-relative-relocs"
        ;;
esac

post_package_strip() {
    if [ -z "$strip_command" ]; then
        strip_command="${OS_TRIPLET}-strip"
    fi

    for f in $(find "${dest_dir}"); do
        if file "$f" | grep 'not stripped' >/dev/null; then
            echo "* stripping '$f'..."
            stripped_file="$(mktemp)"
            ${strip_command} "$f" -o "$stripped_file"
            chmod --reference="$f" "$stripped_file"
            mv -f "$stripped_file" "$f"
        fi
    done
}

autotools_configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    autotools_configure_noflags "$@"
}

autotools_configure_noflags() {
    if [ -z "${configure_script_path}" ]; then
        configure_script_path="${source_dir}/configure"
    fi

        ac_cv_func_malloc_0_nonnull=yes \
        ac_cv_func_calloc_0_nonnull=yes \
        ac_cv_func_realloc_0_nonnull=yes \
    ${configure_script_path} \
        --host=${OS_TRIPLET} \
        --with-sysroot=${sysroot_dir} \
        --prefix=${prefix} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --bindir=${prefix}/bin \
        --sbindir=${prefix}/bin \
        --libdir=${prefix}/lib \
        --disable-static \
        --enable-shared \
        --disable-malloc0returnsnull \
        "$@"
}

autotools_recursive_regen() {
    for f in $(grep -Rl 'GNU config.sub ($timestamp)'); do
        mv "$f" "$f".reference
        cp -v ${base_dir}/build-support/config.sub "$f"
        touch -r "$f".reference "$f"
        rm -f "$f".reference
    done
    for f in $(grep -Rl 'GNU config.guess ($timestamp)'); do
        mv "$f" "$f".reference
        cp -v ${base_dir}/build-support/config.guess "$f"
        touch -r "$f".reference "$f"
        rm -f "$f".reference
    done

    if ! [ -z "$(grep -Rl 'shlibpath_overrides_runpath=no')" ]; then
        if [ -z "$(grep -Rl "dynamic_linker='mlibc ld.so'")" ]; then
            echo "*** Missing libtool support for mlibc - trying to patch support in :3 ***"
            for f in $(grep -Rl "We cannot seem to hardcode it, guess we'll fake it."); do
                mv "$f" "$f".reference
                sed -z \
                    -e 's/add_dir=-L$libdir/add_dir=-L$lt_sysroot$libdir/g' \
                    -e 's/add_dir="-L$libdir"/add_dir="-L$lt_sysroot$libdir"/g' \
                    "$f".reference > "$f"
                chmod --reference="$f".reference "$f"
                touch -r "$f".reference "$f"
                rm -f "$f".reference
            done
            for f in $(grep -Rl 'shlibpath_overrides_runpath=no'); do
                mv "$f" "$f".reference
                sed -z \
                    -e 's/hardcode_into_libs=yes\n  ;;\n\nnewsos6)/hardcode_into_libs=yes\n  ;;\n\n*-mlibc)\n  version_type=linux\n  need_lib_prefix=no\n  need_version=no\n  library_names_spec='"'"'$libname$release$shared_ext$versuffix $libname$release$shared_ext$major $libname$shared_ext'"'"'\n  soname_spec='"'"'$libname$release$shared_ext$major'"'"'\n  dynamic_linker='"'"'mlibc ld.so'"'"'\n  shlibpath_var=LD_LIBRARY_PATH\n  shlibpath_overrides_runpath=no\n  hardcode_into_libs=yes\n  ;;\n\nnewsos6)/g' \
                    -e 's/gnu\*)\n  lt_cv_deplibs_check_method=pass_all\n  ;;/gnu*|*-mlibc)\n  lt_cv_deplibs_check_method=pass_all\n  ;;/g' \
                    -e 's/netbsd\*)\n	;;\n      \*qnx\* | \*nto\*)\n        # QNX uses GNU C/netbsd*|*-mlibc)\n	;;\n      *qnx* | *nto*)\n        # QNX uses GNU C/g' \
                    -e 's/lt_prog_compiler_static='"'"'-Bstatic'"'"'\n      ;;\n\n    \*nto\* | \*qnx\*)\n      # QNX uses GNU C/lt_prog_compiler_static='"'"'-Bstatic'"'"'\n      ;;\n\n    *-mlibc)\n      lt_prog_compiler_wl='"'"'-Wl,'"'"'\n      lt_prog_compiler_pic='"'"'-fPIC'"'"'\n      lt_prog_compiler_static='"'"'-static'"'"'\n      ;;\n\n    *nto* | *qnx*)\n      # QNX uses GNU C/g' \
                    -e 's/ld_shlibs=no\n      fi\n      ;;\n\n    netbsd\*)/ld_shlibs=no\n      fi\n      ;;\n\n    *-mlibc)\n      archive_cmds='"'"'$CC -shared $pic_flag $libobjs $deplibs $compiler_flags $wl-soname $wl$soname -o $lib'"'"'\n      archive_expsym_cmds='"'"'$CC -shared $pic_flag $libobjs $deplibs $compiler_flags $wl-soname $wl$soname $wl-retain-symbols-file $wl$export_symbols -o $lib'"'"'\n      ;;\n\n    netbsd*)/g' \
                    -e 's%netbsd\*)\n      if echo __ELF__ | $CC -E - | $GREP __ELF__ >/dev/null; then\n	archive_cmds='"'"'$LD -Bshareable -o $lib $libobjs $deplibs $linker_flags'"'"'  # a.out%*-mlibc)\n      ;;\n\n    netbsd*)\n      if echo __ELF__ | $CC -E - | $GREP __ELF__ >/dev/null; then\n	archive_cmds='"'"'$LD -Bshareable -o $lib $libobjs $deplibs $linker_flags'"'"'  # a.out%g' \
                    -e 's%netbsd\*)\n        if echo __ELF__ | $CC -E - | $GREP __ELF__ >/dev/null; then\n	  archive_cmds_CXX='"'"'$LD -Bshareable  -o $lib $predep_objects $libobjs $deplibs $postdep_objects $linker_flags'"'"'%*-mlibc)\n	    ld_shlibs_CXX=yes\n	    ;;\n\n      netbsd*)\n        if echo __ELF__ | $CC -E - | $GREP __ELF__ >/dev/null; then\n	  archive_cmds_CXX='"'"'$LD -Bshareable  -o $lib $predep_objects $libobjs $deplibs $postdep_objects $linker_flags'"'"'%g' \
                    "$f".reference > "$f"
                chmod --reference="$f".reference "$f"
                touch -r "$f".reference "$f"
                rm -f "$f".reference
            done
        fi
    fi
}

meson_configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    meson_configure_noflags "$@"
}

meson_configure_noflags() {
    if [ -z "${meson_source_dir}" ]; then
        meson_source_dir="${source_dir}"
    fi

    meson setup "${meson_source_dir}" \
        --cross-file "${base_dir}/build-support/cross_file-$ARCHITECTURE.txt" \
        --prefix=${prefix} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --libdir=lib \
        --sbindir=bin \
        --buildtype=release \
        -Ddefault_library=shared \
        "$@"
}

cmake_configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    cmake_configure_noflags \
        "$@"
}

cmake_configure_noflags() {
    if [ -z "${cmake_source_dir}" ]; then
        cmake_source_dir="${source_dir}"
    fi

    cmake "${cmake_source_dir}" \
        -DCMAKE_TOOLCHAIN_FILE="${base_dir}/build-support/CMakeToolchain-$ARCHITECTURE.txt" \
        -DCMAKE_INSTALL_PREFIX=${prefix} \
        -DCMAKE_INSTALL_SYSCONFDIR=/etc \
        -DCMAKE_INSTALL_LOCALSTATEDIR=/var \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_INSTALL_SBINDIR=bin \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBS=True \
        -DENABLE_STATIC=False \
        -DPKG_CONFIG_EXECUTABLE="/usr/local/bin/$OS_TRIPLET-pkg-config" \
        -GNinja \
        "$@"
}

if [ "$in_container" = true ]; then
    export VMODULES="/tmp/.vmodules"
    mkdir -p "${VMODULES}"/cache
    mkdir -p /tmp/v_$(id -u)
fi

PROD=true
