/* SPDX-License-Identifier: GPL-2.0-or-later */
/* Code generated by tools/agx-re/generate_fake_g17_3d_encoder.py. */
/* Recovered G17 3D ABI SHA-256: c734b6547ea2ae1cd5d33ef19578c8b0615674d87a9ad9785a558998539b88f9 */
#ifndef VINIX_AGX_FAKE_G17_ENCODE_H
#define VINIX_AGX_FAKE_G17_ENCODE_H

#include <stddef.h>
#include <stdint.h>

#include "agx_fake_g17.h"

enum {
    VINIX_FAKE_G17_EXTERNAL_EVENT_COUNT = 2,
    VINIX_FAKE_G17_EXTERNAL_DECISION_COUNT = 0,
    VINIX_FAKE_G17_MAX_WRITES = 404,
};

enum vinix_fake_g17_external_event {
    VINIX_FAKE_G17_EXTERNAL_EVENT_2148 = 0,
    VINIX_FAKE_G17_EXTERNAL_EVENT_2394 = 1,
};

struct vinix_fake_g17_encoder_inputs {
    uint64_t values[VINIX_FAKE_G17_REGISTER_PASSES]
                   [VINIX_FAKE_G17_EXTERNAL_EVENT_COUNT];
    uint32_t column_count;
};

enum vinix_fake_g17_encode_error {
    VINIX_FAKE_G17_ENCODE_OK = 0,
    VINIX_FAKE_G17_ENCODE_INVALID_ARGUMENT = 1,
    VINIX_FAKE_G17_ENCODE_WRITE_CAPACITY = 2,
    VINIX_FAKE_G17_ENCODE_STREAM_OVERFLOW = 3,
    VINIX_FAKE_G17_ENCODE_GRAPH = 4,
};

size_t vinix_fake_g17_encoder_inputs_size(void);

int vinix_fake_g17_encode_3d(
    void *command, size_t command_bytes,
    void *descriptor, size_t descriptor_bytes,
    uint64_t command_gpu_address,
    const struct vinix_fake_g17_encoder_inputs *inputs,
    struct vinix_fake_g17_expected_write *writes,
    uint32_t write_capacity, uint32_t *write_count);

#endif
