/* SPDX-License-Identifier: GPL-2.0-or-later */
#ifndef VINIX_SECURITY_MAC_H
#define VINIX_SECURITY_MAC_H
#define VINIX_MAC_PRCTL 0x56584d41
#define VINIX_MAC_DOMAINS 16U
#define VINIX_MAC_TYPES 32U
#define VINIX_MAC_LABEL_TYPES 29U
#define VINIX_MAC_INSPECT 1U
#define VINIX_MAC_READ 2U
#define VINIX_MAC_WRITE 4U
#define VINIX_MAC_EXECUTE 8U
#define VINIX_MAC_CREATE 16U
#define VINIX_MAC_REMOVE 32U
#define VINIX_MAC_METADATA 64U
#define VINIX_MAC_IOCTL 128U
#define VINIX_MAC_SEARCH 256U
#define VINIX_MAC_ALL 511U
#endif
