module t6050power

import traceanalysis as j

// Public import data comes from the same maintained native contract constants.
pub fn public_constants() map[string]j.Value {
	return {
		'DEFAULT_PREBOOT':                           j.Value('/System/Volumes/Preboot')
		'COMPRESSION_LZFSE':                         j.Value(2049)
		'MAX_DEVICE_TREE_BYTES':                     j.Value(67108864)
		'ADT_PROPERTY_NAME_BYTES':                   j.Value(32)
		'ADT_PROPERTY_LENGTH_MASK':                  j.Value(16777215)
		'PMGR_DEVICE_BYTES':                         j.Value(48)
		'PMGR_DEVICE_HANDLE_OFFSET':                 j.Value(26)
		'PMGR_DEVICE_NAME_OFFSET':                   j.Value(32)
		'PMP_SOC_DEVICE_BYTES':                      j.Value(pmp_soc_device_bytes)
		'PMP_SOC_DEVICE_NAME_OFFSET':                j.Value(116)
		'PMP_PTD_RANGE_BYTES':                       j.Value(32)
		'PMP_PTD_RANGE_NAME_OFFSET':                 j.Value(16)
		'APPLE_PMGR_UUID':                           j.Value(apple_pmgr_uuid)
		'APPLE_T6050_PMGR_UUID':                     j.Value(apple_t6050_pmgr_uuid)
		'APPLE_PMP_UUID':                            j.Value(apple_pmp_uuid)
		'APPLE_PMP_FIRMWARE_UUID':                   j.Value(apple_pmp_firmware_uuid)
		'RTBUDDY_UUID':                              j.Value(rtbuddy_uuid)
		'APPLE_A7IOP_UUID':                          j.Value(apple_a7iop_uuid)
		'APPLE_ASCWRAP_V6_UUID':                     j.Value(apple_ascwrap_v6_uuid)
		'APPLE_T8110_DART_UUID':                     j.Value(apple_t8110_dart_uuid)
		'IODART_FAMILY_UUID':                        j.Value(iodart_family_uuid)
		'T6050_KERNEL_UUID':                         j.Value(t6050_kernel_uuid)
		'DEFAULT_APPLE_PMGR':                        j.Value('build/kext/g17c/driver.ApplePMGR.macho')
		'DEFAULT_APPLE_T6050_PMGR':                  j.Value('build/kext/g17c/driver.AppleT6050PMGR.macho')
		'DEFAULT_APPLE_PMP':                         j.Value('build/kext/g17c/driver.ApplePMP.macho')
		'DEFAULT_APPLE_PMP_FIRMWARE':                j.Value('build/kext/g17c/driver.ApplePMPFirmware.macho')
		'DEFAULT_RTBUDDY':                           j.Value('build/kext/g17c/driver.RTBuddy.macho')
		'DEFAULT_APPLE_A7IOP':                       j.Value('build/kext/g17c/driver.AppleA7IOP.macho')
		'DEFAULT_APPLE_ASCWRAP_V6':                  j.Value('build/kext/g17c/driver.AppleA7IOP-ASCWrap-v6.macho')
		'DEFAULT_APPLE_T8110_DART':                  j.Value('build/kext/g17c/driver.AppleT8110DART.macho')
		'DEFAULT_IODART_FAMILY':                     j.Value('build/kext/g17c/driver.IODARTFamily.macho')
		'DEFAULT_KERNEL':                            j.Value('build/kext/g17c/kernel.macho')
		'PMP_SEND_COMMAND':                          j.Value(pmp_send_command)
		'PMP_WRITE_DASHBOARD':                       j.Value(pmp_write_dashboard)
		'PMP_SET_DEVICE_STATE':                      j.Value(pmp_set_device_state)
		'PMP_SET_VIRTUAL_DEVICE_STATE':              j.Value(pmp_set_virtual_device_state)
		'PMP_INIT_V2':                               j.Value(pmp_init_v2)
		'PMP_GET_DEVICE_INDEX':                      j.Value(pmp_get_device_index)
		'PMP_NOTIFY_INITIAL':                        j.Value(pmp_notify_initial)
		'PMP_WAIT_CLUSTER_POWER_UP':                 j.Value(pmp_wait_cluster_power_up)
		'PMP_ENABLE_DEVICE_GATED':                   j.Value(pmp_enable_device_gated)
		'PMP_DEVICE_ID_TO_DATA':                     j.Value(pmp_device_id_to_data)
		'PMP_CHECK_NOTIFY':                          j.Value(pmp_check_notify)
		'PMP_WAIT_READY':                            j.Value(pmp_wait_ready)
		'PMP_WAIT_READY_V2':                         j.Value(pmp_wait_ready_v2)
		'PMP_READY_GATED':                           j.Value(pmp_ready_gated)
		'PMP_READY_ACTION_V2':                       j.Value(pmp_ready_action_v2)
		'PMP_NOTIFY_INITIAL_ENTRY':                  j.Value(pmp_notify_initial_entry)
		'PMGR_START':                                j.Value(pmgr_start)
		'PMGR_HANDLE_INTERRUPT_ALL':                 j.Value(pmgr_handle_interrupt_all)
		'PMGR_PM_HIBERNATION_STATE':                 j.Value(pmgr_pm_hibernation_state)
		'PMGR_CURRENT_DRIVER_STATE':                 j.Value(pmgr_current_driver_state)
		'PMGR_UPDATE_HIB_DEVICE_STATUS':             j.Value(pmgr_update_hib_device_status)
		'PMGR_INIT_DRIVER':                          j.Value(pmgr_init_driver)
		'PMGR_CONSTRUCTOR':                          j.Value(pmgr_constructor)
		'PMGR_INTERRUPT_CONFIG_PROPERTY':            j.Value(pmgr_interrupt_config_property)
		'PMGR_INTERRUPT_CONFIG_BYTES':               j.Value(pmgr_interrupt_config_bytes)
		'PMGR_INTERRUPT_CONFIG_NAME_OFFSET':         j.Value(pmgr_interrupt_config_name_offset)
		'PMP_READY_INTERRUPT_NAME':                  j.Value(pmp_ready_interrupt_name)
		'APPLE_PTD_READ':                            j.Value(apple_ptd_read)
		'APPLE_PTD_WRITE':                           j.Value(apple_ptd_write)
		'PMGR_GET_REG_MAP':                          j.Value(pmgr_get_reg_map)
		'PMGR_INIT_REG_MAP':                         j.Value(pmgr_init_reg_map)
		'PMGR_WRITE_REG64':                          j.Value(pmgr_write_reg64)
		'APPLE_T6050_PMGR_VTABLE':                   j.Value(apple_t6050_pmgr_vtable)
		'T6050_INIT_REG_MAPS':                       j.Value(t6050_init_reg_maps)
		'T6050_RESTORE_HW':                          j.Value(t6050_restore_hw)
		'T6050_UPDATE_HIB_DEVICE_STATUS':            j.Value(t6050_update_hib_device_status)
		'PMGR_PMP_V1':                               j.Value(pmgr_pmp_v1)
		'PMGR_PMP_V2':                               j.Value(pmgr_pmp_v2)
		'PMGR_GET_NUM_DIES':                         j.Value(pmgr_get_num_dies)
		'PMGR_GET_DIE_COUNT':                        j.Value(pmgr_get_die_count)
		'APPLE_PMP_V2_START':                        j.Value(apple_pmp_v2_start)
		'APPLE_PMP_V2_MESSAGE_HANDLER':              j.Value(apple_pmp_v2_message_handler)
		'APPLE_PMP_V2_HANDLE_MEMORY':                j.Value(apple_pmp_v2_handle_memory)
		'APPLE_PMP_V2_HANDLE_POWER':                 j.Value(apple_pmp_v2_handle_power)
		'APPLE_PMP_V2_HANDLE_REGISTRY':              j.Value(apple_pmp_v2_handle_registry)
		'APPLE_PMP_V2_SEND_MESSAGE':                 j.Value(apple_pmp_v2_send_message)
		'APPLE_PMP_V2_WRITE_DASHBOARD':              j.Value(apple_pmp_v2_write_dashboard)
		'APPLE_PMP_V2_GET_PROPERTY_DATA':            j.Value(apple_pmp_v2_get_property_data)
		'APPLE_PMP_V2_PING_GATED':                   j.Value(apple_pmp_v2_ping_gated)
		'APPLE_PMP_FIRMWARE_VTABLE':                 j.Value(apple_pmp_firmware_vtable)
		'APPLE_PMP_FIRMWARE_START':                  j.Value(apple_pmp_firmware_start)
		'APPLE_PMP_FIRMWARE_PATCH':                  j.Value(apple_pmp_firmware_patch)
		'RTBUDDY_FIRMWARE_SERVICE_VTABLE':           j.Value(rtbuddy_firmware_service_vtable)
		'RTBUDDY_FIRMWARE_VTABLE':                   j.Value(rtbuddy_firmware_vtable)
		'RTBUDDY_FIRMWARE_SERVICE_PRE_LOAD':         j.Value(rtbuddy_firmware_service_pre_load)
		'RTBUDDY_FIRMWARE_SERVICE_PATCH':            j.Value(rtbuddy_firmware_service_patch)
		'RTBUDDY_FIRMWARE_PATCH_U32':                j.Value(rtbuddy_firmware_patch_u32)
		'RTBUDDY_FIRMWARE_FIXUP':                    j.Value(rtbuddy_firmware_fixup)
		'RTBUDDY_FIRMWARE_COPY_TO_TARGET':           j.Value(rtbuddy_firmware_copy_to_target)
		'RTBUDDY_FIRMWARE_CREATE_COREDUMP_MAP':      j.Value(rtbuddy_firmware_create_coredump_map)
		'RTBUDDY_FIRMWARE_PUBLISH':                  j.Value(rtbuddy_firmware_publish)
		'RTBUDDY_FIRMWARE_WRITE_BACK_PATCHBAY':      j.Value(rtbuddy_firmware_write_back_patchbay)
		'RTBUDDY_FIRMWARE_UPDATE_PATCHBAY':          j.Value(rtbuddy_firmware_update_patchbay)
		'RTBUDDY_FIRMWARE_UPDATE_COREDUMP_PATCHBAY': j.Value(rtbuddy_firmware_update_coredump_patchbay)
		'RTBUDDY_FIRMWARE_GET_ROLE':                 j.Value(rtbuddy_firmware_get_role)
		'RTBUDDY_FIRMWARE_ANNOUNCE':                 j.Value(rtbuddy_firmware_announce)
		'RTBUDDY_CALL_PATCHBAY_CALLBACK':            j.Value(rtbuddy_call_patchbay_callback)
		'RTBUDDY_POWER_ON':                          j.Value(rtbuddy_power_on)
		'RTBUDDY_LOAD_FIRMWARE':                     j.Value(rtbuddy_load_firmware)
		'RTBUDDY_VTABLE':                            j.Value(rtbuddy_vtable)
		'RTBUDDY_INIT_CONFIG_EDT':                   j.Value(rtbuddy_init_config_edt)
		'RTBUDDY_ATTEMPT_FIRMWARE_LOAD':             j.Value(rtbuddy_attempt_firmware_load)
		'RTBUDDY_HANDLE_PRELOAD_FIRMWARE':           j.Value(rtbuddy_handle_preload_firmware)
		'RTBUDDY_HANDLE_SERVICE_FIRMWARE':           j.Value(rtbuddy_handle_service_firmware)
		'RTBUDDY_SERVICE_MATCHING_ROLE':             j.Value(rtbuddy_service_matching_role)
		'RTBUDDY_FIRMWARE_PRELOADED':                j.Value(rtbuddy_firmware_preloaded)
		'RTBUDDY_FIRMWARE_INIT_SEGMENT_MAP':         j.Value(rtbuddy_firmware_init_segment_map)
		'RTBUDDY_FIRMWARE_IBOOT_LOADED':             j.Value(rtbuddy_firmware_iboot_loaded)
		'RTBUDDY_FIRMWARE_COPY_ID_BLOCK':            j.Value(rtbuddy_firmware_copy_id_block)
		'RTBUDDY_FIRMWARE_FIND_PATCHBAY':            j.Value(rtbuddy_firmware_find_patchbay)
		'RTBUDDY_FIRMWARE_COPY32_FROM_IOP':          j.Value(rtbuddy_firmware_copy32_from_iop)
		'RTBUDDY_FIRMWARE_SEGMENT_FOR_IOP':          j.Value(rtbuddy_firmware_segment_for_iop)
		'RTBUDDY_SEGMENT_IS_WRITABLE':               j.Value(rtbuddy_segment_is_writable)
		'RTBUDDY_SEGMENT_WITH_PHYSICAL_RANGE':       j.Value(rtbuddy_segment_with_physical_range)
		'RTBUDDY_GET_SEGMENT_MAP':                   j.Value(rtbuddy_get_segment_map)
		'RTBUDDY_PATCHBAY_INIT_WITH_DATA':           j.Value(rtbuddy_patchbay_init_with_data)
		'RTBUDDY_PATCHBAY_FIND':                     j.Value(rtbuddy_patchbay_find)
		'RTBUDDY_PATCHBAY_WITH_DATA':                j.Value(rtbuddy_patchbay_with_data)
		'RTBUDDY_PATCHBAY_GET_BYTES':                j.Value(rtbuddy_patchbay_get_bytes)
		'RTBUDDY_FIRMWARE_GET_PATCHBAY':             j.Value(rtbuddy_firmware_get_patchbay)
		'RTBUDDY_FIRMWARE_COPY_PATCHBAY_DATA':       j.Value(rtbuddy_firmware_copy_patchbay_data)
		'RTBUDDY_FIRMWARE_COPY32_REGION':            j.Value(rtbuddy_firmware_copy32_region)
		'RTBUDDY_COREDUMP_READWRITE_MAP':            j.Value(rtbuddy_coredump_readwrite_map)
		'RTBUDDY_MEMCPY_TO32':                       j.Value(rtbuddy_memcpy_to32)
		'RTK_ID_BLOCK_MAGIC':                        j.Value(rtk_id_block_magic)
		'RTK_ID_BLOCK_BYTES':                        j.Value(rtk_id_block_bytes)
		'RTK_ID_BLOCK_CANDIDATES':                   j.Value(rtk_id_block_candidates)
		'PATCHBAY_HEADER_BYTES':                     j.Value(patchbay_header_bytes)
		'PMP_CHOSEN_PATH':                           j.Value(pmp_chosen_path)
		'PMP_PMGR_PATH':                             j.Value(pmp_pmgr_path)
		'PMP_PROVIDER_NODE':                         j.Value(pmp_provider_node)
		'PMP_MANDATORY_PATCHBAY_INPUTS':             j.Value([
			j.Value([j.Value('BDID'), j.Value('board-id'), j.Value('IODeviceTree:/chosen'),
				j.Value('value'), j.Value(200), j.Value(true)]),
			j.Value([j.Value('DVID'), j.Value('dram-vendor-id'), j.Value('IODeviceTree:/chosen'),
				j.Value('value'), j.Value(204), j.Value(true)]),
			j.Value([j.Value('DCAP'), j.Value('dram-capacity'), j.Value('the RTBuddy provider nub'),
				j.Value('value'), j.Value(208), j.Value(false)]),
			j.Value([j.Value('DCHD'), j.Value('dram-channel-disable'),
				j.Value('the RTBuddy provider nub'), j.Value('value'), j.Value(212), j.Value(false)]),
			j.Value([j.Value('PMC_'), j.Value('pmc'), j.Value('IODeviceTree:/arm-io/pmgr'),
				j.Value('value'), j.Value(216), j.Value(true)]),
			j.Value([j.Value('PMCV'), j.Value('pmc-pmgr'), j.Value('IODeviceTree:/arm-io/pmgr'),
				j.Value('value & 1'), j.Value(220), j.Value(true)]),
			j.Value([j.Value('PMCB'), j.Value('pmc-pmgr'), j.Value('IODeviceTree:/arm-io/pmgr'),
				j.Value('(value >> 3) & 1'), j.Value(224), j.Value(true)]),
			j.Value([j.Value('PMCX'), j.Value('pmc-msg-disabled'), j.Value('the RTBuddy provider nub'),
				j.Value('value'), j.Value(228), j.Value(false)]),
			j.Value([j.Value('CVAR'), j.Value('soc-chip-variant'), j.Value('the RTBuddy provider nub'),
				j.Value('value'), j.Value(232), j.Value(false)]),
		])
		'T6050_PMP_IMAGE_ID_UUID':                   j.Value(t6050_pmp_image_id_uuid)
		'DEFAULT_PMP_IMAGE':                         j.Value('build/firmware/t6050pmp.macho')
		'RTBUDDY_PRELOADED_PROPERTY':                j.Value(rtbuddy_preloaded_property)
		'RTBUDDY_RUNNING_PROPERTY':                  j.Value(rtbuddy_running_property)
		'RTBUDDY_NO_FIRMWARE_SERVICE_PROPERTY':      j.Value(rtbuddy_no_firmware_service_property)
		'RTBUDDY_LOAD_FIRMWARE_GATED':               j.Value(rtbuddy_load_firmware_gated)
		'RTBUDDY_WAIT_FOR_FIRMWARE_SERVICE_GATED':   j.Value(rtbuddy_wait_for_firmware_service_gated)
		'RTBUDDY_PERFORM_POWER_STATE_GATED':         j.Value(rtbuddy_perform_power_state_gated)
		'RTBUDDY_IOP_VALIDATE':                      j.Value(rtbuddy_iop_validate)
		'RTBUDDY_IOP_VALIDATE_POLLING':              j.Value(rtbuddy_iop_validate_polling)
		'RTBUDDY_IOP_VALIDATE_BLOCKING':             j.Value(rtbuddy_iop_validate_blocking)
		'RTBUDDY_SET_IOP_STATUS':                    j.Value(rtbuddy_set_iop_status)
		'RTBUDDY_SET_IOP_STATUS_PUBLIC':             j.Value(rtbuddy_set_iop_status_public)
		'RTBUDDY_MANAGEMENT_HANDLE_HELLO':           j.Value(rtbuddy_management_handle_hello)
		'RTBUDDY_BUILD_ROLL_CALL':                   j.Value(rtbuddy_build_roll_call)
		'RTBUDDY_GET_ENDPOINT':                      j.Value(rtbuddy_get_endpoint)
		'RTBUDDY_MANAGEMENT_HANDLE_EP_ROLLCALL':     j.Value(rtbuddy_management_handle_ep_rollcall)
		'RTBUDDY_CREATE_ENDPOINT':                   j.Value(rtbuddy_create_endpoint)
		'RTBUDDY_ENDPOINT_SERVICE_CREATE_NAME':      j.Value(rtbuddy_endpoint_service_create_name)
		'RTBUDDY_ENDPOINT_GET_SLAVE':                j.Value(rtbuddy_endpoint_get_slave)
		'RTBUDDY_ENDPOINT_INIT_OWNER':               j.Value(rtbuddy_endpoint_init_owner)
		'RTBUDDY_ENDPOINT_SET_POWER_ACTION':         j.Value(rtbuddy_endpoint_set_power_action)
		'APPLE_WRAPPER_MAILBOX_START':               j.Value(apple_wrapper_mailbox_start)
		'APPLE_WRAPPER_MAILBOX_REG':                 j.Value(apple_wrapper_mailbox_reg)
		'APPLE_WRAPPER_MAILBOX_PHYSICAL':            j.Value(apple_wrapper_mailbox_physical)
		'APPLE_A7IOP_VTABLE':                        j.Value(apple_a7iop_vtable)
		'APPLE_A7IOP_START':                         j.Value(apple_a7iop_start)
		'APPLE_A7IOP_HAS_IBOOT_FIRMWARE':            j.Value(apple_a7iop_has_iboot_firmware)
		'APPLE_A7IOP_SEGMENT_RANGES_PROPERTY':       j.Value(apple_a7iop_segment_ranges_property)
		'APPLE_A7IOP_START_CPU_OPTIONS':             j.Value(apple_a7iop_start_cpu_options)
		'APPLE_A7IOP_REG':                           j.Value(apple_a7iop_reg)
		'APPLE_A7IOP_PHYSICAL':                      j.Value(apple_a7iop_physical)
		'APPLE_A7IOP_ENABLE_SRAM':                   j.Value(apple_a7iop_enable_sram)
		'APPLE_A7IOP_ENABLE_POWER':                  j.Value(apple_a7iop_enable_power)
		'APPLE_A7IOP_ENABLE_POWER_VTABLE_SLOT':      j.Value(apple_a7iop_enable_power_vtable_slot)
		'APPLE_A7IOP_DART_MAP_IBOOT_FIRMWARE':       j.Value(apple_a7iop_dart_map_iboot_firmware)
		'IODART_MAPPER_VTABLE':                      j.Value(iodart_mapper_vtable)
		'IODART_MAPPER_GET_PAGE_SIZE':               j.Value(iodart_mapper_get_page_size)
		'IODART_MAPPER_IOVM_INSERT':                 j.Value(iodart_mapper_iovm_insert)
		'IODART_MAPPER_IOVM_INSERT_ONE':             j.Value(iodart_mapper_iovm_insert_one)
		'APPLE_T8110_DART_ENABLE_TRANSLATION':       j.Value(apple_t8110_dart_enable_translation)
		'APPLE_T8110_DART_START':                    j.Value(apple_t8110_dart_start)
		'APPLE_T8110_DART_SETUP':                    j.Value(apple_t8110_dart_setup)
		'APPLE_T8110_DART_GET_SID_PROPERTY':         j.Value(apple_t8110_dart_get_sid_property)
		'APPLE_T8110_DART_GET_SID_COUNT':            j.Value(apple_t8110_dart_get_sid_count)
		'APPLE_T8110_DART_IS_BYPASSED_SID':          j.Value(apple_t8110_dart_is_bypassed_sid)
		'APPLE_T8110_DART_SET_TRANSLATION':          j.Value(apple_t8110_dart_set_translation)
		'APPLE_T8110_DART_SET_TRANSLATION_RANGE':    j.Value(apple_t8110_dart_set_translation_range)
		'APPLE_T8110_DART_INVALIDATE_TLB':           j.Value(apple_t8110_dart_invalidate_tlb)
		'T8110_DART_MAX_TRANSLATION_LEVELS':         j.Value(t8110_dart_max_translation_levels)
		'T8110_DART_VO_TT_INDEX':                    j.Value(t8110_dart_vo_tt_index)
		'T8110_DART_VO_TTE':                         j.Value(t8110_dart_vo_tte)
		'APPLE_ASCWRAP_V6_VTABLE':                   j.Value(apple_ascwrap_v6_vtable)
		'APPLE_ASCWRAP_V6_INITIALIZE':               j.Value(apple_ascwrap_v6_initialize)
		'APPLE_ASCWRAP_V6_SET_IORVBAR':              j.Value(apple_ascwrap_v6_set_iorvbar)
		'APPLE_ASCWRAP_V6_IS_IORVBAR_LOCKED':        j.Value(apple_ascwrap_v6_is_iorvbar_locked)
		'APPLE_ASCWRAP_V6_MAP_FIRMWARE':             j.Value(apple_ascwrap_v6_map_firmware)
		'APPLE_ASCWRAP_V6_RUN_CPU':                  j.Value(apple_ascwrap_v6_run_cpu)
		'APPLE_ASCWRAP_V6_INBOX':                    j.Value(apple_ascwrap_v6_inbox)
		'APPLE_ASCWRAP_V6_OUTBOX':                   j.Value(apple_ascwrap_v6_outbox)
		'APPLE_ASCWRAP_V6_KIC_INBOX_ENABLED':        j.Value(apple_ascwrap_v6_kic_inbox_enabled)
		'APPLE_ASCWRAP_V6_INBOX_EMPTY':              j.Value(apple_ascwrap_v6_inbox_empty)
		'APPLE_ASCWRAP_V6_INBOX_FULL':               j.Value(apple_ascwrap_v6_inbox_full)
		'APPLE_ASCWRAP_V6_OUTBOX_EMPTY':             j.Value(apple_ascwrap_v6_outbox_empty)
		'APPLE_ASCWRAP_V6_MAILBOX_ITEM_SIZE':        j.Value(apple_ascwrap_v6_mailbox_item_size)
	}
}
