// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (c) 2026 Alexander Medvednikov
// Code generated by tools/agx-re/generate_g13_initdata_layout.py; DO NOT EDIT.
//
// G13 InitData field offsets at each firmware ABI, computed from m1n1's
// versioned firmware structures. The 12.3 column reproduces the sizes this
// tree already had, which is what makes the 13.5 column trustworthy.

module fw

// ---- G13 V12_3 ----
pub const g13_v12_3_io_mapping_count = u32(20)
pub const g13_v12_3_globals_size = u64(0x11d40)
pub const g13_v12_3_hw_data_a_size = u64(0x3d6c)
pub const g13_v12_3_hw_data_b_size = u64(0xb6c)
pub const g13_v12_3_io_mapping_size = u64(0x20)
pub const g13_v12_3_power_zone_size = u64(0x20)

// ---- G13 V13_5 ----
pub const g13_v13_5_io_mapping_count = u32(25)
pub const g13_v13_5_globals_size = u64(0x12394)
pub const g13_v13_5_hw_data_a_size = u64(0x421c)
pub const g13_v13_5_hw_data_b_size = u64(0x1884)
pub const g13_v13_5_io_mapping_size = u64(0x20)
pub const g13_v13_5_power_zone_size = u64(0x28)

