// Copyright (c) 2026 Alexander Medvednikov. All rights reserved.
// Use of this source code is governed by a GPL v2 license
// that can be found in the LICENSE file.
module fonthost

fn prelude() []string {
	return [
		'// Copyright (c) 2026 Alexander Medvednikov. All rights reserved.',
		'// Use of this source code is governed by a GPL v2 license',
		'// that can be found in the LICENSE file.',
		'',
		'// Generated by desktop/tools/genfont.py. Do not edit by hand.',
		'//',
		'// Coverage atlases for Roboto with Noto Sans JP and CJK SC fallback; the',
		'// binary needs no font files. Glyph data uses the SIL Open Font License',
		'// 1.1; see desktop/FONT-LICENSE.txt and desktop/FONT-SOURCES.md.',
		'module main',
		'',
		'// FaceBlob is one rasterised face. `bold`, logical `size` and `raster_scale`',
		'// are how the renderer picks between faces. `ascent` + `descent`',
		'// is the height of a line. `parts` join into base64 of a metrics header',
		'// (width, height, left bearing, top bearing, advance for each glyph)',
		'// followed by every glyph\'s coverage bytes in the same order. It is split',
		'// because a single literal this long, spelled as one concatenation,',
		'// exceeds what V\'s checker will descend into.',
		'struct FaceBlob {',
		'\tbold    bool',
		'\tmono    bool',
		'\tsize    int',
		'\traster_scale int',
		'\tascent  int',
		'\tdescent int',
		'\tparts   []string',
		'}',
		'',
		'// Glyph slots run over printable ASCII first, then over these code points',
		'// in this order, in every face. The list is ascending.',
	]
}
