# Defaults chosen for Vinix's framebuffer Xorg and Mesa software renderer.
name = player
video_driver = opengl
screen_w = 1280
screen_h = 720
fullscreen = false
vsync = false
fps_max = 30
pause_fps_max = 15
viewing_range = 48
enable_shaders = false
enable_particles = false
enable_clouds = false
enable_sound = false
enable_ipv6 = false
ipv6_server = false
smooth_lighting = false
cinematic = false
show_debug = false
