// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (c) 2026 Alexander Medvednikov
// Code generated by tools/agx-re/generate_g13_initdata_layout.py; DO NOT EDIT.
//
// G13 InitData field offsets at each firmware ABI, computed from m1n1's
// versioned firmware structures. The 12.3 column reproduces the sizes this
// tree already had, which is what makes the 13.5 column trustworthy.

module fw

// ---- G13 V12_3 ----
pub const g13_v12_3_io_mapping_count = u32(20)
pub const g13_v12_3_globals_size = u64(0x11d40)
pub const g13_v12_3_hw_data_a_size = u64(0x3d6c)
pub const g13_v12_3_hw_data_b_size = u64(0xb6c)
pub const g13_v12_3_io_mapping_size = u64(0x20)
pub const g13_v12_3_power_zone_size = u64(0x20)

// ---- G13 V13_5 ----
pub const g13_v13_5_io_mapping_count = u32(25)
pub const g13_v13_5_globals_size = u64(0x12394)
pub const g13_v13_5_hw_data_a_size = u64(0x421c)
pub const g13_v13_5_hw_data_b_size = u64(0x1884)
pub const g13_v13_5_io_mapping_size = u64(0x20)
pub const g13_v13_5_power_zone_size = u64(0x28)

// Common HwDataB field spans copied from the established 12.3 builder
// into the 13.5 blob. Changed-size arrays are populated separately.
pub const g13_hwdata_b_copy_offsets_v12_3 = [u32(0x8), u32(0x18), u32(0x20), u32(0x28), u32(0x30), u32(0x38), u32(0x40), u32(0x1c8), u32(0x450), u32(0x454), u32(0x458), u32(0x45c), u32(0x460), u32(0x464), u32(0x468), u32(0x46c), u32(0x470), u32(0x474), u32(0x478), u32(0x47c), u32(0x480), u32(0x484), u32(0x488), u32(0x48c), u32(0x490), u32(0x494), u32(0x498), u32(0x49c), u32(0x4a0), u32(0x4a4), u32(0x4a8), u32(0x4ac), u32(0x4b0), u32(0x4b8), u32(0x4bc), u32(0x4c0), u32(0x4c4), u32(0x4c8), u32(0x4cc), u32(0x4d0), u32(0x4d4), u32(0x4d8), u32(0x4dc), u32(0x4e0), u32(0x4e8), u32(0x4ec), u32(0x4f0), u32(0x4f4), u32(0x4f8), u32(0x4fc), u32(0x500), u32(0x504), u32(0x508), u32(0x50c), u32(0x510), u32(0x514), u32(0x518), u32(0x51c), u32(0x520), u32(0x524), u32(0x528), u32(0x52c), u32(0x530), u32(0x534), u32(0x538), u32(0x53c), u32(0x540), u32(0x544), u32(0x548), u32(0x54c), u32(0x550), u32(0x554), u32(0x558), u32(0x560), u32(0x564), u32(0x568), u32(0x56c), u32(0x574), u32(0x5b4), u32(0x7b4), u32(0x9b4), u32(0x9f4), u32(0xa34), u32(0xa74), u32(0xac4), u32(0xacc), u32(0xad0), u32(0xad4), u32(0xae4), u32(0xaf4), u32(0xaf8), u32(0xafc), u32(0xb04), u32(0xb08), u32(0xb0c), u32(0xb10), u32(0xb14), u32(0xb1c), u32(0xb20), u32(0xb24), u32(0xb28), u32(0xb2c), u32(0xb30), u32(0xb34), u32(0xb38), u32(0xb68)]!
pub const g13_hwdata_b_copy_offsets_v13_5 = [u32(0x0), u32(0x8), u32(0x10), u32(0x18), u32(0x20), u32(0x28), u32(0x30), u32(0x638), u32(0x968), u32(0x96c), u32(0x970), u32(0x974), u32(0x978), u32(0x97c), u32(0x980), u32(0x984), u32(0x988), u32(0x98c), u32(0x990), u32(0x994), u32(0x998), u32(0x99c), u32(0x9a0), u32(0x9a4), u32(0x9a8), u32(0x9ac), u32(0x9b0), u32(0x9b4), u32(0x9b8), u32(0x9bc), u32(0x9c0), u32(0x9c4), u32(0x9c8), u32(0x9d0), u32(0x9d4), u32(0x9d8), u32(0x9dc), u32(0x9e0), u32(0x9e4), u32(0x9e8), u32(0x9ec), u32(0x9f0), u32(0x9f4), u32(0x9f8), u32(0xa00), u32(0xa04), u32(0xa08), u32(0xa0c), u32(0xa10), u32(0xa14), u32(0xa18), u32(0xa20), u32(0xa24), u32(0xa28), u32(0xa2c), u32(0xa30), u32(0xa34), u32(0xa38), u32(0xa3c), u32(0xa40), u32(0xa44), u32(0xa48), u32(0xa4c), u32(0xa54), u32(0xa58), u32(0xa5c), u32(0xa60), u32(0xa64), u32(0xa68), u32(0xa6c), u32(0xa70), u32(0xa74), u32(0xa78), u32(0xa80), u32(0xa84), u32(0xa88), u32(0xa8c), u32(0xa90), u32(0xad0), u32(0xcd0), u32(0xf10), u32(0xf50), u32(0xf90), u32(0xfd0), u32(0x16cc), u32(0x16d4), u32(0x16d8), u32(0x16dc), u32(0x16ec), u32(0x16fc), u32(0x1700), u32(0x1704), u32(0x170c), u32(0x1710), u32(0x1714), u32(0x1718), u32(0x171c), u32(0x1724), u32(0x1728), u32(0x172c), u32(0x1730), u32(0x1734), u32(0x1738), u32(0x173c), u32(0x174c), u32(0x177c)]!
pub const g13_hwdata_b_copy_sizes = [u32(0x8), u32(0x8), u32(0x8), u32(0x8), u32(0x8), u32(0x8), u32(0x20), u32(0x8), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x8), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x8), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x8), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x40), u32(0x200), u32(0x200), u32(0x40), u32(0x40), u32(0x40), u32(0x40), u32(0x8), u32(0x4), u32(0x4), u32(0x10), u32(0x10), u32(0x4), u32(0x4), u32(0x8), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x8), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x4), u32(0x30), u32(0x4)]!
pub const g13_v12_3_hw_data_b_io_mappings_offset = u32(0x1d0)
pub const g13_v13_5_hw_data_b_io_mappings_offset = u32(0x640)

// PowerZone member offsets at each ABI. 13.5 inserts two fields in the
// middle of the entry, so the array's stride and the position of the two
// members after the insertion both change: a per-entry base plus fixed
// member offsets would write the filter coefficients into the wrong
// words. The array base itself is in the remap table below.
pub const g13_v12_3_power_zone_val_offset = u32(0x0)
pub const g13_v12_3_power_zone_target_offset = u32(0x4)
pub const g13_v12_3_power_zone_target_off_offset = u32(0x8)
pub const g13_v12_3_power_zone_filter_tc_x4_offset = u32(0xc)
pub const g13_v12_3_power_zone_filter_tc_xperiod_offset = u32(0x10)
pub const g13_v12_3_power_zone_filter_a_neg_offset = u32(0x14)
pub const g13_v12_3_power_zone_filter_a_offset = u32(0x18)
pub const g13_v12_3_power_zone_pad_offset = u32(0x1c)

pub const g13_v13_5_power_zone_val_offset = u32(0x0)
pub const g13_v13_5_power_zone_target_offset = u32(0x4)
pub const g13_v13_5_power_zone_target_off_offset = u32(0x8)
pub const g13_v13_5_power_zone_filter_tc_x4_offset = u32(0xc)
pub const g13_v13_5_power_zone_filter_tc_xperiod_offset = u32(0x10)
pub const g13_v13_5_power_zone_unk_10_offset = u32(0x14)
pub const g13_v13_5_power_zone_unk_14_offset = u32(0x18)
pub const g13_v13_5_power_zone_filter_a_neg_offset = u32(0x1c)
pub const g13_v13_5_power_zone_filter_a_offset = u32(0x20)
pub const g13_v13_5_power_zone_pad_offset = u32(0x24)

// Fields 13.5 adds that need a value written, at their 13.5 offsets.
// These do not exist at 12.3, so there is nothing to translate: the
// builders write them only when the 13.5 layout is selected. Members of
// a nested block are expanded, which is what unk_e10_0 -- the SE control
// block 13.5 grows HwDataA by -- mostly consists of.
pub const g13_v13_5_hwdata_a_clocks_per_period_2_offset = u32(0x8) // u32
pub const g13_v13_5_hwdata_a_ppm_filter_tc_clks_offset = u32(0x74c) // u32
pub const g13_v13_5_hwdata_a_avg_power_target_filter_tc_clks_offset = u32(0xeac) // u32
pub const g13_v13_5_hwdata_a_avg_power_filter_tc_clks_offset = u32(0xfd8) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_0_offset = u32(0x10b4) // Array<0x38, u8>
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_38_offset = u32(0x10ec) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_3c_offset = u32(0x10f0) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_inactive_threshold_offset = u32(0x10f4) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_44_offset = u32(0x10f8) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_engagement_criteria_offset = u32(0x10fc) // i32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_reset_criteria_offset = u32(0x1100) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_50_offset = u32(0x1104) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_54_offset = u32(0x1108) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_58_offset = u32(0x110c) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_5c_offset = u32(0x1110) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_filter_a_neg_offset = u32(0x1114) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_filter_1_a_neg_offset = u32(0x1118) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_filter_a_offset = u32(0x111c) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_filter_1_a_offset = u32(0x1120) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_ki_dt_offset = u32(0x1124) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_ki_1_dt_offset = u32(0x1128) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_78_offset = u32(0x112c) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_7c_offset = u32(0x1130) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_kp_offset = u32(0x1134) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_kp_1_offset = u32(0x1138) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_88_offset = u32(0x113c) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_8c_offset = u32(0x1140) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_max_pstate_scaled_1_offset = u32(0x1144) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_94_offset = u32(0x1148) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_98_offset = u32(0x114c) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_9c_offset = u32(0x1150) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_a0_offset = u32(0x1154) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_a4_offset = u32(0x1158) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_filter_time_constant_ms_offset = u32(0x115c) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_filter_time_constant_1_ms_offset = u32(0x1160) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_filter_time_constant_clks_offset = u32(0x1164) // U64
pub const g13_v13_5_hwdata_a_unk_e10_0_gpu_se_filter_time_constant_1_clks_offset = u32(0x116c) // U64
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_c0_offset = u32(0x1174) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_c4_offset = u32(0x1178) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_c8_offset = u32(0x117c) // Array<0x4c, u8>
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_114_offset = u32(0x11c8) // F32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_118_offset = u32(0x11cc) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_11c_offset = u32(0x11d0) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_120_offset = u32(0x11d4) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_124_offset = u32(0x11d8) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_max_pstate_scaled_2_offset = u32(0x11dc) // u32
pub const g13_v13_5_hwdata_a_unk_e10_0_unk_12c_offset = u32(0x11e0) // Array<0x8c, u8>

pub const g13_v13_5_globals_unk_24_0_offset = u32(0x24) // u32
pub const g13_v13_5_globals_debug_offset = u32(0x2c) // u32
pub const g13_v13_5_globals_unk_2c_0_offset = u32(0x38) // u32
pub const g13_v13_5_globals_unk_89f4_8_offset = u32(0x8aa8) // u32
pub const g13_v13_5_globals_idle_off_standby_timer_offset = u32(0x90c4) // u32
pub const g13_v13_5_globals_unk_hws2_4_offset = u32(0x90c8) // Array<0x8, F32>
pub const g13_v13_5_globals_unk_hws2_24_offset = u32(0x90e8) // u32
pub const g13_v13_5_globals_unk_9010_0_offset = u32(0x914c) // u32
pub const g13_v13_5_globals_unk_1102c_0_offset = u32(0x11184) // u32
pub const g13_v13_5_globals_unk_1102c_4_offset = u32(0x11188) // u32
pub const g13_v13_5_globals_unk_1102c_8_offset = u32(0x1118c) // u32
pub const g13_v13_5_globals_unk_1102c_c_offset = u32(0x11190) // u32
pub const g13_v13_5_globals_cl_kill_timeout_ms_offset = u32(0x11af4) // u32
pub const g13_v13_5_globals_unk_11edc_offset = u32(0x120f0) // u32
pub const g13_v13_5_globals_unk_11efc_offset = u32(0x12110) // u32

pub const g13_v13_5_hwdata_b_unk_arr_0_offset = u32(0x1010) // Array<32, u32>
pub const g13_v13_5_hwdata_b_unk_b38_0_offset = u32(0x1740) // u32
pub const g13_v13_5_hwdata_b_unk_b38_4_offset = u32(0x1744) // u32
pub const g13_v13_5_hwdata_b_unk_c3c_offset = u32(0x1880) // u32

// Where each offset the 12.3 builders write moves to at 13.5. The two
// arrays are index-matched, sorted by the 12.3 offset, and cover exactly
// the offsets those builders address -- generation fails if one of them
// names a field 13.5 removed or reshaped.
pub const g13_hwdata_a_offsets_v12_3 = [u32(0x4), u32(0xc), u32(0x10), u32(0x28), u32(0x2c), u32(0x3c), u32(0x40), u32(0x44), u32(0x4c), u32(0x74), u32(0x64c), u32(0x658), u32(0x660), u32(0x668), u32(0x670), u32(0x674), u32(0x678), u32(0x680), u32(0x684), u32(0x68c), u32(0x698), u32(0x6b8), u32(0x6d4), u32(0x6e0), u32(0x6e8), u32(0x6f0), u32(0x6f8), u32(0x6fc), u32(0x700), u32(0x70c), u32(0x710), u32(0x720), u32(0x728), u32(0x75c), u32(0x764), u32(0x768), u32(0x76c), u32(0x774), u32(0x778), u32(0x77c), u32(0x780), u32(0x784), u32(0x788), u32(0x78c), u32(0x790), u32(0x794), u32(0x798), u32(0x79c), u32(0x7a0), u32(0x7a4), u32(0x7a8), u32(0x7ac), u32(0x7b0), u32(0x7b4), u32(0x7c0), u32(0x7e0), u32(0x7fc), u32(0x800), u32(0x804), u32(0x808), u32(0x818), u32(0x824), u32(0x828), u32(0x830), u32(0x834), u32(0x870), u32(0x878), u32(0x87c), u32(0x880), u32(0x894), u32(0x89c), u32(0x8a8), u32(0x8ac), u32(0x8b8), u32(0x8bc), u32(0x8c0), u32(0x8c4), u32(0x8cc), u32(0x8ec), u32(0xb94), u32(0xc2c), u32(0xc30), u32(0xc34), u32(0xc38), u32(0xc3c), u32(0xc48), u32(0xc4c), u32(0xc50), u32(0xc54), u32(0xc58), u32(0xcf8), u32(0xd04), u32(0xd0c), u32(0xd14), u32(0xd20), u32(0xd24), u32(0xd30), u32(0xd34), u32(0xd38), u32(0xd40), u32(0xd44), u32(0xd4c), u32(0xd64), u32(0xd8c), u32(0xd90), u32(0xd9c), u32(0xda4), u32(0xdac), u32(0xdb8), u32(0xdbc), u32(0xdcc), u32(0xe1c), u32(0xe24), u32(0xe28), u32(0x162c), u32(0x163c), u32(0x3648), u32(0x36e8), u32(0x36f0), u32(0x3718), u32(0x3bf8), u32(0x3ce8), u32(0x3cf4), u32(0x3d14)]!
pub const g13_hwdata_a_offsets_v13_5 = [u32(0x4), u32(0x10), u32(0x14), u32(0x2c), u32(0x30), u32(0x44), u32(0x48), u32(0x4c), u32(0x54), u32(0x80), u32(0x658), u32(0x664), u32(0x66c), u32(0x674), u32(0x67c), u32(0x680), u32(0x684), u32(0x68c), u32(0x690), u32(0x698), u32(0x6a4), u32(0x6d4), u32(0x6f0), u32(0x6fc), u32(0x704), u32(0x70c), u32(0x714), u32(0x718), u32(0x71c), u32(0x728), u32(0x72c), u32(0x73c), u32(0x744), u32(0x788), u32(0x790), u32(0x794), u32(0x798), u32(0x7a0), u32(0x7a4), u32(0x7a8), u32(0x7ac), u32(0x7b0), u32(0x7b4), u32(0x7b8), u32(0x7bc), u32(0x7c0), u32(0x7c4), u32(0x7c8), u32(0x7cc), u32(0x7d0), u32(0x7d4), u32(0x7d8), u32(0x7dc), u32(0x7e0), u32(0x7ec), u32(0x81c), u32(0x838), u32(0x83c), u32(0x840), u32(0x844), u32(0x854), u32(0x860), u32(0x864), u32(0x86c), u32(0x870), u32(0x8ac), u32(0x8b4), u32(0x8b8), u32(0x8bc), u32(0x8d0), u32(0x8d8), u32(0x8e4), u32(0x8e8), u32(0x8f4), u32(0x8f8), u32(0x8fc), u32(0x900), u32(0x908), u32(0x938), u32(0xbe0), u32(0xe80), u32(0xe84), u32(0xe88), u32(0xe8c), u32(0xe90), u32(0xe9c), u32(0xea0), u32(0xea4), u32(0xea8), u32(0xeb4), u32(0xf7c), u32(0xf88), u32(0xf90), u32(0xf98), u32(0xfa4), u32(0xfa8), u32(0xfb4), u32(0xfb8), u32(0xfbc), u32(0xfc4), u32(0xfc8), u32(0xfd0), u32(0xff8), u32(0x1020), u32(0x1024), u32(0x1030), u32(0x1038), u32(0x1040), u32(0x104c), u32(0x1050), u32(0x1060), u32(0x1278), u32(0x1280), u32(0x1284), u32(0x1a88), u32(0x1a90), u32(0x3a9c), u32(0x3b3c), u32(0x3b64), u32(0x3b8c), u32(0x406c), u32(0x4160), u32(0x416c), u32(0x418c)]!

pub const g13_globals_offsets_v12_3 = [u32(0x28), u32(0x2c), u32(0x34), u32(0x54), u32(0x56), u32(0x58), u32(0x5e), u32(0x66), u32(0x8900), u32(0x8908), u32(0x890c), u32(0x8910), u32(0x891c), u32(0x8924), u32(0x8928), u32(0x892c), u32(0x8930), u32(0x8934), u32(0x8938), u32(0x893c), u32(0x89bc), u32(0x89c0), u32(0x89c4), u32(0x89c8), u32(0x89cc), u32(0x89d0), u32(0x89e0), u32(0x89e4), u32(0x89e8), u32(0x89ec), u32(0x89f8), u32(0x8a98), u32(0x8aa0), u32(0x8fa8), u32(0x900c), u32(0x10e84), u32(0x11020), u32(0x11024), u32(0x11028), u32(0x11030), u32(0x11034), u32(0x11038), u32(0x118e0)]!
pub const g13_globals_offsets_v13_5 = [u32(0x34), u32(0x3c), u32(0x44), u32(0x64), u32(0x66), u32(0x68), u32(0x6e), u32(0x82), u32(0x8970), u32(0x8978), u32(0x897c), u32(0x8980), u32(0x898c), u32(0x8994), u32(0x8998), u32(0x899c), u32(0x89a0), u32(0x89a4), u32(0x89a8), u32(0x89ac), u32(0x8a68), u32(0x8a6c), u32(0x8a70), u32(0x8a74), u32(0x8a78), u32(0x8a7c), u32(0x8a8c), u32(0x8a90), u32(0x8a94), u32(0x8a98), u32(0x8b0c), u32(0x8bac), u32(0x8bb4), u32(0x90bc), u32(0x9148), u32(0x10fdc), u32(0x11178), u32(0x1117c), u32(0x11180), u32(0x1119c), u32(0x111a0), u32(0x111a4), u32(0x11af0)]!

// 12.3 offsets whose field 13.5 does not have. The write is skipped
// there rather than failing: the value has nowhere to go, and putting
// it at the 12.3 offset would land on whatever 13.5 placed there.
pub const g13_hwdata_a_offsets_dropped_v13_5 = [u32(0x1634)]
pub const g13_globals_offsets_dropped_v13_5 = []u32{}

