#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
. "$repo/build-support/find-v.sh"
# V internally consults VEXE; keep it bound to the selected compiler too.
export VEXE="$V"
source=
keep=
while [ "$#" -gt 0 ]; do
    case "$1" in
        --source) source=$2; shift 2 ;;
        --keep-dir) keep=$2; shift 2 ;;
        *) echo "usage: $0 [--source /immutable/config_test.c] [--keep-dir /new/evidence-dir]" >&2; exit 2 ;;
    esac
done
if [ -n "$keep" ]; then
    mkdir "$keep"
    work=$(CDPATH= cd -- "$keep" && pwd)
else
    work=$(mktemp -d "${TMPDIR:-/tmp}/vinix-pci-config.XXXXXX")
    trap 'rm -rf "$work"' EXIT HUP INT TERM
fi
case "$(uname -m)" in
    arm64|aarch64) v_arch=arm64 ;;
    x86_64|amd64) v_arch=amd64 ;;
    *) echo "unsupported host architecture" >&2; exit 2 ;;
esac
V_C_ERROR_BUG_REPORT_DISABLED=1 "$V" -shared -no-builtin -os vinix \
    -target-libc-headers -nofloat -gc none -manualfree \
    -o "$work/core.c" "$repo/kernel/pci/config_core.v"
if [ -z "$source" ]; then
    python3 "$repo/build-support/compile-v-module.py" \
        "$repo/tests/pci-config/configfixture" "$work/fixture.c" --arch "$v_arch" -d nofloat
    # Repair only duplicate forward typedef scaffolding emitted by this V build.
    # Preserve the raw generated bytes; no function body or assertion is edited.
    cp "$work/fixture.c" "$work/fixture-raw.c"
    python3 - "$work" <<'PYABI'
from pathlib import Path
import hashlib, json, re, sys
work = Path(sys.argv[1])
raw = (work/"fixture-raw.c").read_text()
allowed = {"Actor", "CommandCase", "Interior", "Observed", "TestDevice"}
seen, removed, lines = set(), [], []
for line in raw.splitlines(keepends=True):
    match = re.fullmatch(r"typedef struct configfixture__(\w+) configfixture__\1;\n", line)
    if match and match[1] in allowed:
        if line in seen:
            removed.append(line.rstrip("\n"))
            continue
        seen.add(line)
    lines.append(line)
if len(removed) > len(allowed) or len(set(removed)) != len(removed):
    raise SystemExit("unexpected repeated V forward typedef scaffolding")
normalized = "".join(lines)
(work/"fixture.c").write_text(normalized)
(work/"typedef-normalization.json").write_text(json.dumps({
    "removed_byte_identical_lines": removed,
    "raw_sha256": hashlib.sha256(raw.encode()).hexdigest(),
    "normalized_sha256": hashlib.sha256(normalized.encode()).hexdigest(),
}, indent=2)+"\n")
PYABI
    fixture_source=$work/fixture.c
else
    fixture_source=$(python3 - "$source" <<'PY'
from pathlib import Path
import sys
source = Path(sys.argv[1]).resolve(strict=True)
if not source.is_file():
    raise SystemExit("control source is not a file")
print(source)
PY
)
fi
python3 - "$repo" "$work" "$fixture_source" "$source" "$V" "${CC:-clang}" <<'PY'
from pathlib import Path
import hashlib, json, os, subprocess, sys
repo, work, fixture, original, v, cc = sys.argv[1:]
paths = [Path(repo) / name for name in (
    "kernel/pci/config_core.v", "kernel/c/pci_config.h", "tests/pci-config/run.sh",
    "build-support/find-v.sh", "build-support/compile-v-module.py")]
paths.extend((Path(work)/"core.c", Path(fixture)))
if not original:
    paths.extend(sorted((Path(repo)/"tests/pci-config/configfixture").glob("*")))
record = {"fixture": "original-C" if original else "maintained-V", "host": os.uname().machine,
          "v_version": subprocess.check_output([v, "version"], text=True).strip(),
          "cc_version": subprocess.check_output([cc, "--version"], text=True).splitlines()[0],
          "sanitizers": ["address", "undefined"],
          "asan_options": os.environ.get("ASAN_OPTIONS", "detect_leaks=0:halt_on_error=1"),
          "ubsan_options": os.environ.get("UBSAN_OPTIONS", "halt_on_error=1"),
          "inputs": {str(p): {"sha256": hashlib.sha256(p.read_bytes()).hexdigest(),
                              "bytes": p.stat().st_size} for p in paths}}
(Path(work)/"inputs.json").write_text(json.dumps(record, indent=2)+"\n")
PY
for dialect in gnu99 gnu11; do
    "${CC:-clang}" -std="$dialect" -O1 -g -Wall -Wextra -Werror -Wno-unused-function -pthread \
        -I "$repo/kernel/c" -ffreestanding -fno-builtin -fno-strict-aliasing \
        -fsanitize=address,undefined -fno-omit-frame-pointer \
        -Dmalloc=vinix_pci_test_malloc -Dcalloc=vinix_pci_test_calloc \
        -Drealloc=vinix_pci_test_realloc -Dfree=vinix_pci_test_free \
        -c "$work/core.c" -o "$work/core-$dialect.o"
    if [ -z "$source" ]; then
        "${CC:-clang}" -std="$dialect" -O1 -g -Wall -Wextra -Werror -pthread \
            -Wno-unused-function -Wno-unused-parameter -fPIC \
            -idirafter "$repo/kernel/c" -I "$repo/tests/pci-config/configfixture" \
            -fsanitize=address,undefined -fno-omit-frame-pointer \
            -c "$fixture_source" -o "$work/fixture-$dialect.o"
        fixture_input=$work/fixture-$dialect.o
    else
        fixture_input=$fixture_source
    fi
    "${CC:-clang}" -std="$dialect" -O1 -g -Wall -Wextra -Werror -pthread \
        -fsanitize=address,undefined -fno-omit-frame-pointer \
        "$fixture_input" "$work/core-$dialect.o" -o "$work/test-$dialect"
    if ASAN_OPTIONS="${ASAN_OPTIONS:-detect_leaks=0:halt_on_error=1}" \
       UBSAN_OPTIONS="${UBSAN_OPTIONS:-halt_on_error=1}" "$work/test-$dialect" \
           > "$work/test-$dialect.log" 2>&1; then
        cat "$work/test-$dialect.log"
    else
        status=$?
        cat "$work/test-$dialect.log"
        exit "$status"
    fi
done
