@[has_globals]
module driver

// Top-level GPU driver probe and registration
// Discovers the Apple AGX GPU from the device tree, initializes all
// subsystems (UAT, channels, firmware, RTKit), creates the
// GpuManager, and registers a DRM driver with GEM, render, and compute
// capabilities.
import gpu.agx.gpu
import gpu.agx.hw
import gpu.agx.regs
import gpu.agx.mmu
import gpu.agx.pgtable
import gpu.agx.event
import gpu.agx.fw
import gpu.agx.file as agx_file
import gpu.dcp
import drm
import drm.ioctl as drm_ioctl
import apple.rtkit
import devicetree
import memory

pub struct AgxDriver {
pub mut:
	gpu         &gpu.GpuManager = unsafe { nil }
	dcp         &dcp.AppleDCP = unsafe { nil }
	drm_dev     &drm.DrmDevice = unsafe { nil }
	hw_config   hw.HwConfig
	detected    bool
	initialized bool
}

__global (
	agx_driver_inst AgxDriver
)

struct PlatformResources {
pub:
	asc_base        u64
	sgx_base        u64
	sgx_size        u64
	mailbox_base    u64
	handoff_base    u64
	handoff_size    u64
	pagetables_base u64
	pagetables_size u64
	ttbs_base       u64
	ttbs_size       u64
}

fn find_gpu_node() ?(&devicetree.DTNode, u32, bool) {
	// Apple DeviceTree uses gpu,tXXXX. Older downstream FDTs generated by
	// m1n1 used apple,agx-tXXXX, so retain both spellings.
	if node := devicetree.find_compatible('gpu,t6050') {
		return node, u32(0x6050), true
	}
	if node := devicetree.find_compatible('apple,agx-t6050') {
		return node, u32(0x6050), false
	}
	if node := devicetree.find_compatible('gpu,t8103') {
		return node, u32(0x8103), true
	}
	if node := devicetree.find_compatible('apple,agx-t8103') {
		return node, u32(0x8103), false
	}
	return none
}

fn find_native_asc_node() ?&devicetree.DTNode {
	if node := devicetree.find_node('/arm-io/gfx-asc') {
		return node
	}
	if node := devicetree.find_node('/soc/gfx-asc') {
		return node
	}
	return none
}

fn get_platform_resources(gpu_node &devicetree.DTNode, native_adt bool) ?PlatformResources {
	gpu_regs := devicetree.get_translated_reg_ranges(gpu_node) or {
		println('agx: failed to translate GPU register ranges')
		return none
	}
	if native_adt {
		if gpu_regs.len == 0 {
			println('agx: native SGX node has no registers')
			return none
		}
		asc_node := find_native_asc_node() or {
			println('agx: native gfx-asc node not found')
			return none
		}
		asc_regs := devicetree.get_translated_reg_ranges(asc_node) or {
			println('agx: failed to translate native gfx-asc registers')
			return none
		}
		if asc_regs.len == 0 || asc_regs[0].size < 0x9000 {
			println('agx: native gfx-asc register window is incomplete')
			return none
		}
		ttbs_base := devicetree.get_le_u64(gpu_node, 'gpu-region-base') or {
			println('agx: native SGX node has no gpu-region-base')
			return none
		}
		ttbs_size := devicetree.get_le_u64(gpu_node, 'gpu-region-size') or {
			println('agx: native SGX node has no gpu-region-size')
			return none
		}
		handoff_base := devicetree.get_le_u64(gpu_node, 'gfx-handoff-base') or {
			println('agx: native SGX node has no gfx-handoff-base')
			return none
		}
		handoff_size := devicetree.get_le_u64(gpu_node, 'gfx-handoff-size') or {
			println('agx: native SGX node has no gfx-handoff-size')
			return none
		}
		pagetables_base := devicetree.get_le_u64(gpu_node, 'gfx-shared-region-base') or {
			println('agx: native SGX node has no gfx-shared-region-base')
			return none
		}
		pagetables_size := devicetree.get_le_u64(gpu_node, 'gfx-shared-region-size') or {
			println('agx: native SGX node has no gfx-shared-region-size')
			return none
		}
		return PlatformResources{
			asc_base: asc_regs[0].base
			sgx_base: gpu_regs[0].base
			sgx_size: gpu_regs[0].size
			mailbox_base: asc_regs[0].base + 0x8000
			handoff_base: handoff_base
			handoff_size: handoff_size
			pagetables_base: pagetables_base
			pagetables_size: pagetables_size
			ttbs_base: ttbs_base
			ttbs_size: ttbs_size
		}
	}

	asc := devicetree.get_named_reg(gpu_node, 'asc') or {
		if gpu_regs.len < 1 {
			println('agx: GPU node has no ASC register range')
			return none
		}
		gpu_regs[0]
	}
	sgx := devicetree.get_named_reg(gpu_node, 'sgx') or {
		if gpu_regs.len < 2 {
			println('agx: GPU node has no SGX register range')
			return none
		}
		gpu_regs[1]
	}
	mailbox_node := devicetree.get_phandle_node(gpu_node, 'mboxes', 0) or {
		println('agx: GPU mailbox phandle is missing')
		return none
	}
	mailbox_regs := devicetree.get_translated_reg_ranges(mailbox_node) or {
		println('agx: failed to translate GPU mailbox registers')
		return none
	}
	if mailbox_regs.len == 0 {
		println('agx: GPU mailbox has no register range')
		return none
	}
	ttbs_node := devicetree.get_named_phandle_node(gpu_node, 'memory-region', 'memory-region-names', 'ttbs') or {
		println('agx: GPU TTB reserved-memory region is missing')
		return none
	}
	ttbs_regs := devicetree.get_translated_reg_ranges(ttbs_node) or {
		println('agx: failed to translate GPU TTB region')
		return none
	}
	handoff_node := devicetree.get_named_phandle_node(gpu_node, 'memory-region', 'memory-region-names', 'handoff') or {
		println('agx: GPU handoff reserved-memory region is missing')
		return none
	}
	handoff_regs := devicetree.get_translated_reg_ranges(handoff_node) or {
		println('agx: failed to translate GPU handoff region')
		return none
	}
	pagetables_node := devicetree.get_named_phandle_node(gpu_node, 'memory-region', 'memory-region-names', 'pagetables') or {
		println('agx: GPU page-table reserved-memory region is missing')
		return none
	}
	pagetables_regs := devicetree.get_translated_reg_ranges(pagetables_node) or {
		println('agx: failed to translate GPU page-table region')
		return none
	}
	if ttbs_regs.len == 0 || handoff_regs.len == 0 || pagetables_regs.len == 0 {
		println('agx: GPU reserved-memory region has no address')
		return none
	}
	return PlatformResources{
		asc_base: asc.base
		sgx_base: sgx.base
		sgx_size: sgx.size
		mailbox_base: mailbox_regs[0].base
		handoff_base: handoff_regs[0].base
		handoff_size: handoff_regs[0].size
		pagetables_base: pagetables_regs[0].base
		pagetables_size: pagetables_regs[0].size
		ttbs_base: ttbs_regs[0].base
		ttbs_size: ttbs_regs[0].size
	}
}

// The unprefixed performance properties are Apple DeviceTree binary records,
// not big-endian FDT cells. Each record is { frequency_hz, voltage_mv } in
// little endian, grouped as one complete state table per GPU partition.
fn load_t6050_performance_config(gpu_node &devicetree.DTNode, mut cfg hw.HwConfig) bool {
	state_count := devicetree.get_le_u32(gpu_node, 'perf-state-count') or {
		println('agx: t6050 has no perf-state-count')
		return false
	}
	table_count := devicetree.get_le_u32(gpu_node, 'perf-state-table-count') or {
		println('agx: t6050 has no perf-state-table-count')
		return false
	}
	max_state := devicetree.get_le_u32(gpu_node, 'gpu-num-perf-states') or {
		println('agx: t6050 has no gpu-num-perf-states')
		return false
	}
	base_state := devicetree.get_le_u32(gpu_node, 'gpu-perf-base-pstate') or {
		println('agx: t6050 has no gpu-perf-base-pstate')
		return false
	}
	if state_count == 0 || state_count > 16 || table_count == 0 || table_count > 16
		|| max_state + 1 != state_count || base_state == 0 || base_state >= max_state {
		C.printf(c'agx: invalid t6050 performance dimensions states=%u tables=%u base=%u max=%u\n', state_count, table_count, base_state, max_state)
		return false
	}
	states := devicetree.get_le_u32_array(gpu_node, 'perf-states') or {
		println('agx: t6050 has no perf-states')
		return false
	}
	sram_states := devicetree.get_le_u32_array(gpu_node, 'perf-states-sram') or {
		println('agx: t6050 has no perf-states-sram')
		return false
	}
	expected_words := int(state_count * table_count * 2)
	if states.len != expected_words || sram_states.len != expected_words {
		C.printf(c'agx: invalid t6050 performance table lengths core=%u sram=%u expected=%u\n', u32(states.len), u32(sram_states.len), u32(expected_words))
		return false
	}

	for table := u32(0); table < table_count; table++ {
		for state := u32(0); state < state_count; state++ {
			source := int((table * state_count + state) * 2)
			destination := state * 16 + table
			frequency := states[source]
			if table == 0 {
				cfg.perf_state_frequencies[state] = frequency
			} else if frequency != cfg.perf_state_frequencies[state] {
				C.printf(c'agx: t6050 performance table %u state %u has mismatched frequency\n', table, state)
				return false
			}
			if sram_states[source] != frequency {
				C.printf(c'agx: t6050 SRAM table %u state %u has mismatched frequency\n', table, state)
				return false
			}
			cfg.perf_state_voltages[destination] = states[source + 1]
			cfg.perf_state_sram_voltages[destination] = sram_states[source + 1]
		}
	}
	cfg.perf_state_count = state_count
	cfg.perf_state_table_count = table_count
	cfg.perf_state_base = base_state
	C.printf(c'agx: loaded %u x %u native performance states (%u..%u MHz)\n', state_count, table_count, cfg.perf_state_frequencies[0] / 1000000, cfg.perf_state_frequencies[state_count - 1] / 1000000)
	return true
}

// The auxiliary clock-domain format recovered from Apple's G17 producer is:
// {rail_count, state_count}, followed by voltage_uV/frequency_Hz pairs for
// each rail, then one default SRAM voltage_uV per rail. The producer converts
// voltages to mV and clamps SRAM voltage to max(core, default).
fn load_t6050_aux_performance_domain(gpu_node &devicetree.DTNode, name string) ?hw.AuxPerfStateConfig {
	values := devicetree.get_le_u64_array(gpu_node, name) or {
		println('agx: t6050 has no ${name}')
		return none
	}
	if values.len < 2 || values[0] == 0 || values[0] > 2 || values[1] == 0
		|| values[1] > 16 {
		C.printf(c'agx: invalid t6050 %s dimensions\n', name.str)
		return none
	}
	table_count := u32(values[0])
	state_count := u32(values[1])
	expected_values := 2 + int(table_count) * (int(state_count) * 2 + 1)
	if values.len != expected_values {
		C.printf(c'agx: invalid t6050 %s length=%u expected=%u\n', name.str, u32(values.len), u32(expected_values))
		return none
	}

	mut result := hw.AuxPerfStateConfig{
		state_count: state_count
		table_count: table_count
	}
	for table := u32(0); table < table_count; table++ {
		for state := u32(0); state < state_count; state++ {
			source := 2 + int((table * state_count + state) * 2)
			voltage_uv := values[source]
			frequency := values[source + 1]
			if voltage_uv % 1_000 != 0 || voltage_uv / 1_000 > 0xffff_ffff
				|| frequency > 0xffff_ffff {
				C.printf(c'agx: invalid t6050 %s state value\n', name.str)
				return none
			}
			if table == 0 {
				result.frequencies[state] = u32(frequency)
			} else if frequency != result.frequencies[state] {
				C.printf(c'agx: t6050 %s table %u state %u has mismatched frequency\n', name.str, table, state)
				return none
			}
			result.voltages[state * 2 + table] = u32(voltage_uv / 1_000)
		}
	}

	defaults_base := 2 + int(table_count * state_count * 2)
	for table := u32(0); table < table_count; table++ {
		default_uv := values[defaults_base + int(table)]
		if default_uv % 1_000 != 0 || default_uv / 1_000 > 0xffff_ffff {
			C.printf(c'agx: invalid t6050 %s SRAM default\n', name.str)
			return none
		}
		default_mv := u32(default_uv / 1_000)
		for state := u32(0); state < state_count; state++ {
			index := state * 2 + table
			core_mv := result.voltages[index]
			result.sram_voltages[index] = if core_mv > default_mv { core_mv } else { default_mv }
		}
	}
	return result
}

fn load_t6050_aux_performance_config(gpu_node &devicetree.DTNode, mut cfg hw.HwConfig) bool {
	cs := load_t6050_aux_performance_domain(gpu_node, 'cs-perf-states') or { return false }
	afr := load_t6050_aux_performance_domain(gpu_node, 'afr-perf-states') or { return false }
	cfg.cs_perf_states = cs
	cfg.afr_perf_states = afr
	C.printf(c'agx: loaded native CS/AFR performance states (%u/%u states)\n', cs.state_count, afr.state_count)
	return true
}

// Probe GPU from device tree and bring up all supported subsystems.
pub fn initialise() {
	println('agx: Probing Apple GPU')

	// Step 1: Find and identify the GPU node.
	gpu_node, chip_id, native_adt := find_gpu_node() or {
		println('agx: GPU not found in device tree')
		return
	}
	mut cfg := hw.get_config(chip_id) or {
		C.printf(c'agx: No hardware configuration for chip 0x%x\n', chip_id)
		return
	}
	if chip_id == 0x6050 {
		if !load_t6050_performance_config(gpu_node, mut cfg)
			|| !load_t6050_aux_performance_config(gpu_node, mut cfg) {
			println('agx: t6050 performance configuration is incomplete')
			return
		}
	}
	if !drm_ioctl.validate_asahi_25_layouts() {
		println('agx: Mesa 25.0.5 DRM UAPI layout validation failed')
		return
	}

	if chip_id == 0x6050 {
		if !fw.validate_g17_bootstrap_allocations() || !fw.validate_g17_accelerator_layouts()
			|| !fw.validate_g17_channel_layouts() {
			println('agx: internal G17 firmware layout validation failed')
			return
		}
		C.printf(c'agx: detected t6050 / G17C, %u cores in %u GPU partitions\n', cfg.gpu_core_count, cfg.num_mgpus)
	} else {
		C.printf(c'agx: detected chip 0x%x, %u cores\n', chip_id, cfg.gpu_core_count)
	}

	// Step 2: Resolve all addresses without touching hardware. Native Apple
	// nodes and m1n1/Linux nodes expose different layouts.
	platform := get_platform_resources(gpu_node, native_adt) or {
		println('agx: platform resources are incomplete')
		return
	}
	cfg.gpu_mmio_base = platform.sgx_base
	cfg.gpu_mmio_size = platform.sgx_size
	agx_driver_inst.hw_config = cfg
	agx_driver_inst.detected = true
	if platform.ttbs_size < 64 * 16 {
		println('agx: TTB region is too small for 64 UAT contexts')
		return
	}
	if platform.handoff_size < sizeof(mmu.UatHandoff) || platform.pagetables_size < pgtable.uat_pgsz {
		println('agx: UAT handoff or page-table reserved region is too small')
		return
	}
	C.printf(c'agx: ASC=0x%llx SGX=0x%llx mailbox=0x%llx TTBs=0x%llx+0x%llx\n', platform.asc_base, platform.sgx_base, platform.mailbox_base, platform.ttbs_base, platform.ttbs_size)
	C.printf(c'agx: UAT handoff=0x%llx+0x%llx page tables=0x%llx+0x%llx\n', platform.handoff_base, platform.handoff_size, platform.pagetables_base, platform.pagetables_size)

	// Never run a newer GPU with the byte layouts and register sequence for
	// M1. Detection is useful for bring-up logs, but writes here could corrupt
	// firmware-owned memory or wedge the machine.
	if !cfg.can_boot_firmware() {
		C.printf(c'agx: chip 0x%x firmware ABI is not implemented; leaving hardware untouched\n', chip_id)
		return
	}

	// Step 3: Initialize the AGX-internal UAT from its reserved TTB region.
	handoff_abi := if cfg.firmware_abi == .g17_26_5_partial {
		mmu.UatHandoffAbi.g17_26_5
	} else {
		mmu.UatHandoffAbi.v12_3
	}
	_ := mmu.new_manager(platform.ttbs_base, platform.handoff_base, platform.pagetables_base, cfg.uat_ias, cfg.uat_oas, cfg.map_kernel_to_user, handoff_abi) or {
		println('agx: Failed to initialize UAT manager')
		return
	}

	// Step 4: Initialize GPU event stamp storage.
	stamp_pages := u64(mmu.uat_num_contexts)
	stamp_phys := u64(memory.pmm_alloc_aligned(stamp_pages, 4))
	if stamp_phys == 0 {
		println('agx: Failed to allocate stamp memory')
		return
	}
	stamp_va := u64(0x10_0000)
	stamp_size := stamp_pages * page_size
	if uat_mgr != unsafe { nil } {
		if !uat_mgr.map_kernel(stamp_va, stamp_phys, stamp_size, pgtable.gpu_prot_fw_gpu_shared_rw) {
			println('agx: Failed to map stamp buffer in UAT')
			return
		}
	}
	gpu_event_mgr = event.new_event_manager(stamp_va, stamp_phys)

	// Step 5: Create GPU resources, RTKit, and GpuManager.
	gpu_res := regs.new_resources(platform.asc_base, platform.sgx_base)
	gpu_rtk := rtkit.new_rtkit(platform.mailbox_base, 'agx')

	mut mgr := gpu.new_gpu_manager(&gpu_res, &cfg, &gpu_rtk) or {
		println('agx: Failed to create GPU manager')
		return
	}

	// Step 6: Init GPU (RTKit boot, firmware init)
	if !mgr.init() {
		println('agx: GPU initialization failed')
		return
	}

	agx_driver_inst.gpu = &mgr
	gpu.set_global_manager(agx_driver_inst.gpu)

	// Step 7: Register DRM driver (name "asahi", features GEM|RENDER|COMPUTE)
	agx_drm_driver := &drm.DrmDriver{
		name: 'asahi'
		desc: 'Apple AGX GPU'
		major: 1
		minor: 0
		patchlevel: 0
		features: drm.driver_gem | drm.driver_render | drm.driver_compute
		ioctls: agx_file.drm_ioctls()
		file_close: agx_file.release_handle
	}

	agx_driver_inst.drm_dev = drm.register_driver(agx_drm_driver) or {
		println('agx: Failed to register DRM driver')
		return
	}

	agx_driver_inst.initialized = true

	// Step 8: Log success
	println('agx: Apple GPU driver initialized successfully')
	println('agx: DRM device registered as card${agx_driver_inst.drm_dev.dev_id}')
}

// Tear down the GPU driver and release all resources.
pub fn shutdown() {
	if !agx_driver_inst.initialized {
		return
	}

	println('agx: Shutting down Apple GPU driver')

	// Unregister DRM device
	if agx_driver_inst.drm_dev != unsafe { nil } {
		drm.unregister_device(agx_driver_inst.drm_dev)
		agx_driver_inst.drm_dev = unsafe { nil }
	}

	// Shutdown GPU manager (stops firmware, ASC)
	if agx_driver_inst.gpu != unsafe { nil } {
		mut g := unsafe { agx_driver_inst.gpu }
		g.shutdown()
		gpu.set_global_manager(unsafe { nil })
		agx_driver_inst.gpu = unsafe { nil }
	}

	agx_driver_inst.initialized = false
	println('agx: GPU driver shutdown complete')
}
