@[has_globals]
module driver

// Top-level GPU driver probe and registration
// Discovers the Apple AGX GPU from the device tree, initializes all
// subsystems (DART, UAT, channels, firmware, RTKit), creates the
// GpuManager, and registers a DRM driver with GEM, render, and compute
// capabilities.

import gpu.agx.gpu
import gpu.agx.hw
import gpu.agx.regs
import gpu.agx.mmu
import gpu.agx.event
import gpu.agx.file as agx_file
import gpu.dcp
import drm
import apple.rtkit
import apple.dart
import devicetree
import klock
import memory

pub struct AgxDriver {
pub mut:
	gpu         &gpu.GpuManager = unsafe { nil }
	dcp         &dcp.AppleDCP   = unsafe { nil }
	drm_dev     &drm.DrmDevice  = unsafe { nil }
	hw_config   hw.HwConfig
	detected    bool
	initialized bool
}

__global (
	agx_driver_inst AgxDriver
)

fn find_gpu_node() ?(&devicetree.DTNode, u32) {
	// Apple DeviceTree uses gpu,tXXXX. Older downstream FDTs generated by
	// m1n1 used apple,agx-tXXXX, so retain both spellings.
	if node := devicetree.find_compatible('gpu,t6050') {
		return node, u32(0x6050)
	}
	if node := devicetree.find_compatible('apple,agx-t6050') {
		return node, u32(0x6050)
	}
	if node := devicetree.find_compatible('gpu,t8103') {
		return node, u32(0x8103)
	}
	if node := devicetree.find_compatible('apple,agx-t8103') {
		return node, u32(0x8103)
	}
	return none
}

// Probe GPU from device tree and bring up all supported subsystems.
pub fn initialise() {
	println('agx: Probing Apple GPU')

	// Step 1: Find and identify the GPU node.
	gpu_node, chip_id := find_gpu_node() or {
		println('agx: GPU not found in device tree')
		return
	}
	cfg := hw.get_config(chip_id) or {
		C.printf(c'agx: No hardware configuration for chip 0x%x\n', chip_id)
		return
	}
	agx_driver_inst.hw_config = cfg
	agx_driver_inst.detected = true

	if chip_id == 0x6050 {
		C.printf(c'agx: detected t6050 / G17C, %u cores in %u GPU partitions\n',
			cfg.gpu_core_count, cfg.num_mgpus)
	} else {
		C.printf(c'agx: detected chip 0x%x, %u cores\n', chip_id, cfg.gpu_core_count)
	}

	// Step 2: Get registers from device tree
	gpu_regs := devicetree.get_reg(gpu_node) or {
		println('agx: Failed to get GPU registers from device tree')
		return
	}

	if gpu_regs.len < 2 {
		println('agx: Insufficient register ranges in device tree')
		return
	}

	gpu_base := gpu_regs[0]

	// Never run a newer GPU with the byte layouts and register sequence for
	// M1. Detection is useful for bring-up logs, but writes here could corrupt
	// firmware-owned memory or wedge the machine.
	if !cfg.can_boot_firmware() {
		C.printf(c'agx: chip 0x%x firmware ABI is not implemented; leaving hardware untouched\n',
			chip_id)
		return
	}

	// Find ASC mailbox and DART from device tree
	asc_node := devicetree.find_compatible('apple,asc-mailbox') or {
		println('agx: ASC mailbox not found in device tree')
		return
	}
	asc_regs := devicetree.get_reg(asc_node) or {
		println('agx: Failed to get ASC registers')
		return
	}
	asc_base := asc_regs[0]

	dart_node := devicetree.find_compatible('apple,t8103-dart') or {
		println('agx: DART not found in device tree')
		return
	}
	dart_regs := devicetree.get_reg(dart_node) or {
		println('agx: Failed to get DART registers')
		return
	}
	dart_base := dart_regs[0]

	// Step 4: Init DART for GPU
	mut gpu_dart := dart.new_dart(dart_base, 0)
	gpu_dart.init()
	println('agx: DART IOMMU initialized')

	// Step 5: Init UAT manager
	ttbat_base := gpu_base + 0x100000
	_ := mmu.new_manager(ttbat_base) or {
		println('agx: Failed to initialize UAT manager')
		return
	}

	// Step 6: Init GPU resources (event manager)
	stamp_pages := u64(mmu.uat_num_contexts)
	stamp_phys := u64(memory.pmm_alloc(stamp_pages))
	if stamp_phys == 0 {
		println('agx: Failed to allocate stamp memory')
		return
	}
	stamp_va := u64(0x10_0000)
	stamp_size := stamp_pages * page_size
	if !gpu_dart.map(stamp_va, stamp_phys, stamp_size) {
		println('agx: Failed to map stamp buffer in DART')
		return
	}
	if uat_mgr != unsafe { nil } {
		if !uat_mgr.map_kernel(stamp_va, stamp_phys, stamp_size, 0x43) {
			println('agx: Failed to map stamp buffer in UAT')
			return
		}
	}
	gpu_event_mgr = event.new_event_manager(stamp_va, stamp_phys)

	// Step 7: Create GPU resources, RTKit, and GpuManager
	gpu_res := regs.new_resources(gpu_base)
	gpu_rtk := rtkit.new_rtkit(asc_base, 'agx')

	mut mgr := gpu.new_gpu_manager(&gpu_res, &cfg, &gpu_rtk, &gpu_dart) or {
		println('agx: Failed to create GPU manager')
		return
	}

	// Step 8: Init GPU (RTKit boot, firmware init)
	if !mgr.init() {
		println('agx: GPU initialization failed')
		return
	}

	agx_driver_inst.gpu = &mgr
	gpu.set_global_manager(agx_driver_inst.gpu)

	// Step 10: Register DRM driver (name "asahi", features GEM|RENDER|COMPUTE)
	agx_drm_driver := &drm.DrmDriver{
		name:       'asahi'
		desc:       'Apple AGX GPU'
		major:      1
		minor:      0
		patchlevel: 0
		features:   drm.driver_gem | drm.driver_render | drm.driver_compute
		ioctls:     agx_file.drm_ioctls()
		file_close: agx_file.release_handle
	}

	agx_driver_inst.drm_dev = drm.register_driver(agx_drm_driver) or {
		println('agx: Failed to register DRM driver')
		return
	}

	agx_driver_inst.initialized = true

	// Step 11: Log success
	println('agx: Apple GPU driver initialized successfully')
	println('agx: DRM device registered as card${agx_driver_inst.drm_dev.dev_id}')
}

// Tear down the GPU driver and release all resources.
pub fn shutdown() {
	if !agx_driver_inst.initialized {
		return
	}

	println('agx: Shutting down Apple GPU driver')

	// Unregister DRM device
	if agx_driver_inst.drm_dev != unsafe { nil } {
		drm.unregister_device(agx_driver_inst.drm_dev)
		agx_driver_inst.drm_dev = unsafe { nil }
	}

	// Shutdown GPU manager (stops firmware, ASC)
	if agx_driver_inst.gpu != unsafe { nil } {
		mut g := unsafe { agx_driver_inst.gpu }
		g.shutdown()
		gpu.set_global_manager(unsafe { nil })
		agx_driver_inst.gpu = unsafe { nil }
	}

	agx_driver_inst.initialized = false
	println('agx: GPU driver shutdown complete')
}
