#!/usr/bin/env python3
"""Rasterise the Roboto faces the desktop draws with into a V source file.

Vinix has no font files and no rasteriser, so the glyphs travel with the
binary: every face is baked here into an 8-bit coverage atlas and emitted as
base64, which keeps font_data.v small enough to compile quickly while staying
plain text in the repository.

Run from the repository root after changing a size or adding a face:

    python3 desktop/tools/genfont.py

Roboto is licensed under the SIL Open Font License 1.1; the atlas is a
derivative of it and carries the same license (see desktop/FONT-LICENSE.txt).
"""

import base64
import os
import sys

from PIL import ImageFont

FIRST_CHAR = 32
LAST_CHAR = 126
GLYPH_COUNT = LAST_CHAR - FIRST_CHAR + 1

# The fonts ship with ui2, which is a git worktree inside this repository.
FONT_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "third_party", "ui2",
    "assets", "fonts",
)

# name, file, pixel size
FACES = [
    ("small", "Roboto-Regular.ttf", 11),
    ("ui", "Roboto-Regular.ttf", 13),
    ("bold", "Roboto-Bold.ttf", 13),
    ("clock", "Roboto-Bold", 17),
]


def build_face(file_name, size):
    path = os.path.join(FONT_DIR, file_name)
    if not path.endswith(".ttf"):
        path += ".ttf"
    if not os.path.exists(path):
        sys.exit("font not found: %s" % path)
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()

    header = bytearray()
    pixels = bytearray()

    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        ch = chr(code)
        bbox = font.getbbox(ch)
        advance = int(round(font.getlength(ch)))
        mask = font.getmask(ch, mode="L")
        width, height = mask.size

        if width == 0 or height == 0:
            header += bytes([0, 0, 0, 0, advance & 0xFF])
            continue

        # getbbox measures from the top of the line box, which is where the
        # renderer places a run, so no baseline arithmetic is needed at
        # runtime.
        bx = bbox[0]
        by = bbox[1]
        if bx < -128 or bx > 127:
            sys.exit("left bearing out of range for %r" % ch)
        header += bytes([width, height, bx & 0xFF, by & 0xFF, advance & 0xFF])
        pixels += bytes(mask)

    return {
        "ascent": ascent,
        "descent": descent,
        "blob": base64.b64encode(bytes(header + pixels)).decode("ascii"),
    }


def wrap(text, width=100):
    return [text[i:i + width] for i in range(0, len(text), width)]


def main():
    out = []
    out.append("// Generated by desktop/tools/genfont.py. Do not edit by hand.")
    out.append("//")
    out.append("// Coverage atlases for the Roboto faces the desktop draws with, so the")
    out.append("// binary needs no font file on a system that has none. Roboto is licensed")
    out.append("// under the SIL Open Font License 1.1; see desktop/FONT-LICENSE.txt.")
    out.append("module main")
    out.append("")
    out.append("// FaceBlob is one rasterised face: `ascent` + `descent` is the height of a")
    out.append("// line, and `parts` join into base64 of a %d entry metrics header (width," % GLYPH_COUNT)
    out.append("// height, left bearing, top bearing, advance) followed by every glyph's")
    out.append("// coverage bytes in the same order. It is split because a single literal")
    out.append("// this long, spelled as one concatenation, exceeds what V's checker will")
    out.append("// descend into.")
    out.append("struct FaceBlob {")
    out.append("\tascent  int")
    out.append("\tdescent int")
    out.append("\tparts   []string")
    out.append("}")
    out.append("")
    out.append("const font_first_char = %d" % FIRST_CHAR)
    out.append("const font_last_char = %d" % LAST_CHAR)
    out.append("")

    names = []
    for name, file_name, size in FACES:
        face = build_face(file_name, size)
        names.append(name)
        out.append("// %s: %s at %dpx" % (name, file_name, size))
        out.append("const face_%s = FaceBlob{" % name)
        out.append("\tascent:  %d" % face["ascent"])
        out.append("\tdescent: %d" % face["descent"])
        out.append("\tparts:   [")
        for line in wrap(face["blob"]):
            out.append("\t\t'%s'," % line)
        out.append("\t]")
        out.append("}")
        out.append("")

    out.append("// font_blobs is indexed by the Face enum in font.v.")
    out.append("const font_blobs = [")
    for name in names:
        out.append("\tface_%s," % name)
    out.append("]")
    out.append("")

    target = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "font_data.v")
    with open(target, "w") as handle:
        handle.write("\n".join(out))
    print("wrote %s (%d bytes)" % (os.path.normpath(target), os.path.getsize(target)))


if __name__ == "__main__":
    main()
