#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Stage the committed V software presenter and generated ABI for host tests.

Usage: stage_host_gpu.py <staged-desktop-directory> [--v /path/to/v]
The generated V flag file links the object in all subsequent V test builds.
"""

import argparse
import os
from pathlib import Path
import platform
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]


def git(*arguments):
    return subprocess.check_output(["git", "-C", str(ROOT), *arguments])


def stage(destination, compiler, v=None, revision="HEAD"):
    destination = destination.resolve()
    if destination == ROOT or destination == ROOT / "desktop":
        raise ValueError("Use a build staging directory for generated presenter artifacts")
    destination.mkdir(parents=True, exist_ok=True)
    revision = git("rev-parse", revision + "^{commit}").decode().strip()
    environment = os.environ.copy()
    if v:
        candidate = Path(v)
        if candidate.is_dir():
            candidate = candidate / "v"
        environment["V"] = str(candidate.resolve()) if candidate.is_file() else (shutil.which(v) or v)
    with tempfile.TemporaryDirectory(prefix="vinix-host-gpu-") as temporary:
        source_root = Path(temporary)
        paths = git("ls-tree", "-rz", "--name-only", revision, "desktop/gpucore").decode().split("\0")
        paths += ["build-support/compile-v-module.py", "build-support/find-v.sh"]
        for name in filter(None, paths):
            target = source_root / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(git("show", revision + ":" + name))
        source = destination / "gpu-present-host.c"
        header = destination / "gpu_present.h"
        # Remove old staged source symlinks before writing build artifacts.
        source.unlink(missing_ok=True)
        header.unlink(missing_ok=True)
        arch = "arm64" if platform.machine().lower() in ("arm64", "aarch64") else "amd64"
        subprocess.run(["python3", str(source_root / "build-support/compile-v-module.py"),
                        str(source_root / "desktop/gpucore"), str(source), "--arch", arch,
                        "--header", str(header)], check=True, env=environment)
    artifact = destination / "gpu-present-host.o"
    subprocess.run([compiler, "-std=c11", "-O2", "-D_GNU_SOURCE", "-Wno-unused-function",
                    "-Wno-unused-label", "-Wno-unused-parameter", "-c", str(source),
                    "-o", str(artifact)], check=True)
    flags = destination / "gpu_present_host_flags.v"
    flags.unlink(missing_ok=True)
    flags.write_text("// Generated by stage_host_gpu.py from committed desktop/gpucore.\n"
                     "module main\n#flag @VMODROOT/gpu-present-host.o\n")
    (destination / "gpu-present-host.revision").write_text(revision + "\n")
    print("Host software presenter staged from " + revision[:8])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("destination", type=Path)
    parser.add_argument("--cc", default=os.environ.get("CC", "clang"))
    parser.add_argument("--v", default=os.environ.get("V"))
    parser.add_argument("--revision", default="HEAD", help="Committed presenter revision to freeze")
    args = parser.parse_args()
    stage(args.destination, args.cc, args.v, args.revision)
