PS1='\[\033[01;32m\]root@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '
HISTCONTROL=ignoredups
HISTSIZE=-1
HISTFILESIZE=-1
alias ls="ls --color=auto"

export DISPLAY=:0
alias 1="X &"
alias 2="twm &"
alias 3="xeyes &"
