// SPDX-License-Identifier: GPL-2.0-or-later
module fetchcore

import androidhost as ah
import json2

fn select_libraries(version ah.Value) !ah.Value {
	mut mojang := []ah.Value{}
	mut modules := []ah.Value{}
	for library in iterable(item(version, ah.Value('libraries'))!)! {
		name := item(library, ah.Value('name'))!
		parts := method('split', [name, ah.Value(':')])!
		group := item(parts, ah.Value(0))!
		artifact := item(parts, ah.Value(1))!
		classifier := if compare('gt', builtin('len', parts)!, ah.Value(3))! {
			item(parts, ah.Value(3))!
		} else {
			null()
		}
		if equal(group, ah.Value('org.lwjgl'))! {
			pair := ah.Value([artifact, item(parts, ah.Value(2))!])
			mut present := false
			for old in modules {
				if equal(old, pair)! {
					present = true
					break
				}
			}
			if !present { modules << pair }
			if classifier !is json2.Null && truth(method('startswith', [classifier,
				ah.Value('natives-')])!)! {
				continue
			}
		}
		if !truth(public('rule_allows', [
			argument('value', get(library, 'rules', null())!),
			argument('value', ah.Value(map[string]ah.Value{})),
		], false)!)! {
			continue
		}
		artifact_download := get(get(library, 'downloads', ah.Value(map[string]ah.Value{}))!, 'artifact', null())!
		if artifact_download is json2.Null { continue }
		mojang << ah.Value({
			'name': name
			'path': item(artifact_download, ah.Value('path'))!
			'url':  item(artifact_download, ah.Value('url'))!
			'sha1': item(artifact_download, ah.Value('sha1'))!
		})
	}
	mut natives := []ah.Value{}
	for pair in builtin('sorted', ah.Value(modules))!.items() {
		artifact := stringify(item(pair, ah.Value(0))!)!
		version_text := stringify(item(pair, ah.Value(1))!)!
		classifier_name := stringify(constant('NATIVES_CLASSIFIER')!)!
		coordinate := 'org.lwjgl:' + artifact + ':' + version_text + ':' + classifier_name
		value := public('maven_path', [argument('value', ah.Value(coordinate))], false)!
		url := stringify(constant('MAVEN_CENTRAL')!)! + '/' + stringify(value)!
		mut missing := false
		mut cause := ?IError(none)
		payload := fetch_api(ah.Value(url + '.sha1')) or {
			if err is BindingError && truth(ah.field(err.value, 'runtime_error'))! {
				missing = true
			} else {
				cause = err
			}
			''
		}
		if failure := cause { return failure }
		if missing {
			log('  no ' + stringify(constant('NATIVES_CLASSIFIER')!)! + ' for ' + artifact + ' ' + version_text)!
			continue
		}
		decoded := callback('bytes_method', {
			'data':   ah.Value(payload)
			'method': ah.Value('decode')
		})!
		checksum := method('strip', [item(method('split', [decoded])!, ah.Value(0))!])!
		natives << ah.Value({
			'name': ah.Value(coordinate)
			'path': value
			'url':  ah.Value(url)
			'sha1': checksum
		})
	}
	return ah.Value([ah.Value(mojang), ah.Value(natives)])
}

fn launch_environment(destination string, settings map[string]ah.Value) ! {
	version := ah.field(settings, 'version')
	args := get(version, 'arguments', ah.Value(map[string]ah.Value{}))!
	jvm := public('flatten_arguments', [
		argument('value', get(args, 'jvm', ah.Value([]ah.Value{}))!),
		argument('value', ah.Value(map[string]ah.Value{})),
	], false)!
	mut filtered := []ah.Value{}
	mut skip_next := false
	for argument_value in iterable(jvm)! {
		if skip_next {
			skip_next = false
			continue
		}
		if equal(argument_value, ah.Value('-cp'))! {
			skip_next = true
			continue
		}
		filtered << argument_value
	}
	demo := public('flatten_arguments', [
		argument('value', get(get(version, 'arguments', ah.Value(map[string]ah.Value{}))!, 'game', ah.Value([]ah.Value{}))!),
		argument('value', ah.Value({
			'is_demo_user':          ah.Value(true)
			'has_custom_resolution': ah.Value(true)
		})),
	], false)!
	full := public('flatten_arguments', [
		argument('value', get(get(version, 'arguments', ah.Value(map[string]ah.Value{}))!, 'game', ah.Value([]ah.Value{}))!),
		argument('value', ah.Value({
			'is_demo_user':          ah.Value(false)
			'has_custom_resolution': ah.Value(true)
		})),
	], false)!
	game_root := ah.field(settings, 'game_root')
	mut lines := ['# Generated by build-support/minecraft/fetch-minecraft.py — do not edit.']
	lines << environment_line('MC_VERSION', ah.field(settings, 'version_id'))!
	lines << environment_line('MC_VERSION_TYPE', item(version, ah.Value('type'))!)!
	lines << environment_line('MC_MAIN_CLASS', item(version, ah.Value('mainClass'))!)!
	lines << environment_line('MC_ASSET_INDEX', ah.field(settings, 'asset_index'))!
	lines << environment_line('MC_GAME_ROOT', game_root)!
	lines << environment_line('MC_JAVA_MAJOR', ah.Value(stringify(get(get(version, 'javaVersion', ah.Value(map[string]ah.Value{}))!, 'majorVersion', ah.Value(21))!)!))!
	mut classpath := []ah.Value{}
	for entry in iterable(ah.field(settings, 'classpath'))! {
		classpath << ah.Value(stringify(game_root)! + '/' + stringify(entry)!)
	}
	lines << environment_line('MC_CLASSPATH', method('join', [ah.Value(':'), ah.Value(classpath)])!)!
	lines << environment_line('MC_JVM_ARGS', method('join', [ah.Value(' '), ah.Value(filtered)])!)!
	lines << environment_line('MC_GAME_ARGS_DEMO', method('join', [ah.Value(' '), demo])!)!
	lines << environment_line('MC_GAME_ARGS_FULL', method('join', [ah.Value(' '), full])!)!
	path('write_text', destination, [ah.Value(lines.join('\n') + '\n')], map[string]ah.Value{})!
}

fn environment_line(name string, value ah.Value) !string {
	return name + '=' + public('shell_quote', [argument('value', value)], false)!.text()
}
