name: Nightly Vinix rebuild

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  check-build-needed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check if build is necessary
        run: test "$(git tag --points-at HEAD)" = ""

  vinix-build:
    needs: check-build-needed
    name: Build ${{ matrix.release_arch }} desktop ISO
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64
            release_arch: amd64
          - architecture: aarch64
            release_arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install make diffutils curl git rsync xorriso -y

      - name: Enable user namespaces
        run: sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0

      - name: Build full desktop distro and ISO
        run: ARCHITECTURE=${{ matrix.architecture }} JINX_CLEAN_WORKDIRS=yes PKGS_TO_INSTALL='*' make all

      - name: Rename ISO
        run: mv vinix.iso vinix-nightly-${{ matrix.release_arch }}-desktop-$(date +'%Y%m%d').iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: vinix-${{ matrix.release_arch }}-desktop
          path: vinix-nightly-${{ matrix.release_arch }}-desktop-*.iso
          if-no-files-found: error

  publish-nightly:
    needs: vinix-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download desktop ISOs
        uses: actions/download-artifact@v4
        with:
          path: nightly-artifacts

      - name: Set TAG_DATE variable
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Tag new nightly release
        run: git tag nightly-$TAG_DATE && git push --tags

      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          name: Nightly desktop build ${{ env.TAG_DATE }}
          tag_name: nightly-${{ env.TAG_DATE }}
          body: Desktop-enabled AMD64 and ARM64 images of the current Vinix nightly build.
          files: nightly-artifacts/**/*.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
