name: Weekly Vinix rebuild

on:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  vinix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unshallow repo tags
        run: git fetch --prune --unshallow --tags

      - name: Check if build is necessary
        run: test "$(git tag --points-at HEAD)" = ""

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install make diffutils curl git rsync xorriso -y

      #- name: Build full distro and ISO
      #  run: PKGS_TO_INSTALL='*' make all

      #- name: Rename vinix.iso
      #  run: mv vinix.iso vinix-weekly-full-$(date +'%Y%m%d').iso

      - name: Build base distro and ISO
        run: make all

      - name: Rename vinix.iso
        run: mv vinix.iso vinix-weekly-base-$(date +'%Y%m%d').iso

      - name: Set TAG_DATE variable
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Tag new weekly release
        run: git tag weekly-$TAG_DATE && git push --tags

      - name: Create weekly release
        uses: softprops/action-gh-release@v2
        with:
          name: Weekly build ${{ env.TAG_DATE }}
          tag_name: weekly-${{ env.TAG_DATE }}
          body: Image of an up to date Vinix weekly build.
          files: |
            vinix-weekly-*.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
